using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Settlements.Locations
{
	// Token: 0x02000368 RID: 872
	public class Location
	{
		// Token: 0x0600332D RID: 13101 RVA: 0x000D4E4A File Offset: 0x000D304A
		internal static void AutoGeneratedStaticCollectObjectsLocation(object o, List<object> collectedObjects)
		{
			((Location)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600332E RID: 13102 RVA: 0x000D4E58 File Offset: 0x000D3058
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._overriddenName);
			collectedObjects.Add(this._overriddenDoorName);
			collectedObjects.Add(this.SpecialItems);
		}

		// Token: 0x0600332F RID: 13103 RVA: 0x000D4E7E File Offset: 0x000D307E
		internal static object AutoGeneratedGetMemberValueStringId(object o)
		{
			return ((Location)o).StringId;
		}

		// Token: 0x06003330 RID: 13104 RVA: 0x000D4E8B File Offset: 0x000D308B
		internal static object AutoGeneratedGetMemberValueSpecialItems(object o)
		{
			return ((Location)o).SpecialItems;
		}

		// Token: 0x06003331 RID: 13105 RVA: 0x000D4E98 File Offset: 0x000D3098
		internal static object AutoGeneratedGetMemberValueIsReserved(object o)
		{
			return ((Location)o).IsReserved;
		}

		// Token: 0x06003332 RID: 13106 RVA: 0x000D4EAA File Offset: 0x000D30AA
		internal static object AutoGeneratedGetMemberValue_overriddenName(object o)
		{
			return ((Location)o)._overriddenName;
		}

		// Token: 0x06003333 RID: 13107 RVA: 0x000D4EB7 File Offset: 0x000D30B7
		internal static object AutoGeneratedGetMemberValue_overriddenDoorName(object o)
		{
			return ((Location)o)._overriddenDoorName;
		}

		// Token: 0x17000C8F RID: 3215
		// (get) Token: 0x06003334 RID: 13108 RVA: 0x000D4EC4 File Offset: 0x000D30C4
		// (set) Token: 0x06003335 RID: 13109 RVA: 0x000D4ECC File Offset: 0x000D30CC
		[SaveableProperty(10)]
		public string StringId { get; private set; }

		// Token: 0x17000C90 RID: 3216
		// (get) Token: 0x06003336 RID: 13110 RVA: 0x000D4ED5 File Offset: 0x000D30D5
		// (set) Token: 0x06003337 RID: 13111 RVA: 0x000D4EDD File Offset: 0x000D30DD
		[SaveableProperty(20)]
		public List<ItemObject> SpecialItems { get; private set; }

		// Token: 0x17000C91 RID: 3217
		// (get) Token: 0x06003338 RID: 13112 RVA: 0x000D4EE6 File Offset: 0x000D30E6
		// (set) Token: 0x06003339 RID: 13113 RVA: 0x000D4EEE File Offset: 0x000D30EE
		[SaveableProperty(30)]
		public bool IsReserved { get; private set; }

		// Token: 0x17000C92 RID: 3218
		// (get) Token: 0x0600333A RID: 13114 RVA: 0x000D4EF7 File Offset: 0x000D30F7
		// (set) Token: 0x0600333B RID: 13115 RVA: 0x000D4EFF File Offset: 0x000D30FF
		public List<Location> LocationsOfPassages { get; private set; }

		// Token: 0x17000C93 RID: 3219
		// (get) Token: 0x0600333C RID: 13116 RVA: 0x000D4F08 File Offset: 0x000D3108
		public TextObject Name
		{
			get
			{
				if (!TextObject.IsNullOrEmpty(this._overriddenName))
				{
					return this._overriddenName;
				}
				return this._name;
			}
		}

		// Token: 0x17000C94 RID: 3220
		// (get) Token: 0x0600333D RID: 13117 RVA: 0x000D4F24 File Offset: 0x000D3124
		public TextObject DoorName
		{
			get
			{
				if (!TextObject.IsNullOrEmpty(this._overriddenDoorName))
				{
					return this._overriddenDoorName;
				}
				return this._doorName;
			}
		}

		// Token: 0x17000C95 RID: 3221
		// (get) Token: 0x0600333E RID: 13118 RVA: 0x000D4F40 File Offset: 0x000D3140
		// (set) Token: 0x0600333F RID: 13119 RVA: 0x000D4F48 File Offset: 0x000D3148
		public bool IsIndoor { get; private set; }

		// Token: 0x17000C96 RID: 3222
		// (get) Token: 0x06003340 RID: 13120 RVA: 0x000D4F51 File Offset: 0x000D3151
		// (set) Token: 0x06003341 RID: 13121 RVA: 0x000D4F59 File Offset: 0x000D3159
		public bool CanBeReserved { get; private set; }

		// Token: 0x17000C97 RID: 3223
		// (get) Token: 0x06003342 RID: 13122 RVA: 0x000D4F62 File Offset: 0x000D3162
		// (set) Token: 0x06003343 RID: 13123 RVA: 0x000D4F6A File Offset: 0x000D316A
		[CachedData]
		public bool IsInitialized { get; private set; }

		// Token: 0x17000C98 RID: 3224
		// (get) Token: 0x06003344 RID: 13124 RVA: 0x000D4F73 File Offset: 0x000D3173
		public int CharacterCount
		{
			get
			{
				return this._characterList.Count;
			}
		}

		// Token: 0x06003345 RID: 13125 RVA: 0x000D4F80 File Offset: 0x000D3180
		public Location(string stringId, TextObject name, TextObject doorName, int prosperityMax, bool isIndoor, bool canBeReserved, string playerCanEnter, string playerCanSee, string aiCanExit, string aiCanEnter, string[] sceneNames, LocationComplex locationComplex)
		{
			this.ProsperityMax = prosperityMax;
			this._characterList = new List<LocationCharacter>();
			this.LocationsOfPassages = new List<Location>();
			this.SpecialItems = new List<ItemObject>();
			this.StringId = stringId;
			this._name = name;
			this._doorName = doorName;
			this.IsIndoor = isIndoor;
			this.CanBeReserved = canBeReserved;
			this.IsReserved = false;
			this._aiCanEnter = aiCanEnter;
			this._playerCanEnter = playerCanEnter;
			this._playerCanSee = playerCanSee;
			this._aiCanExit = aiCanExit;
			this._ownerComplex = locationComplex;
			this._overriddenName = TextObject.Empty;
			this._overriddenDoorName = TextObject.Empty;
			this._sceneNames = new string[4];
			for (int i = 0; i < 4; i++)
			{
				this._sceneNames[i] = sceneNames[i];
			}
		}

		// Token: 0x06003346 RID: 13126 RVA: 0x000D504C File Offset: 0x000D324C
		public Location(Location location, LocationComplex locationComplex) : this(location.StringId, location.Name, location.DoorName, location.ProsperityMax, location.IsIndoor, location.CanBeReserved, location._playerCanEnter, location._playerCanSee, location._aiCanExit, location._aiCanEnter, location._sceneNames, locationComplex)
		{
		}

		// Token: 0x06003347 RID: 13127 RVA: 0x000D50A4 File Offset: 0x000D32A4
		public void Initialize(Location locationTemplate, LocationComplex ownerComplex)
		{
			this.ProsperityMax = locationTemplate.ProsperityMax;
			this.LocationsOfPassages = new List<Location>();
			this._name = locationTemplate.Name;
			this._doorName = locationTemplate.DoorName;
			this.IsIndoor = locationTemplate.IsIndoor;
			this.CanBeReserved = locationTemplate.CanBeReserved;
			this._aiCanEnter = locationTemplate._aiCanEnter;
			this._playerCanEnter = locationTemplate._playerCanEnter;
			this._playerCanSee = locationTemplate._playerCanSee;
			this._aiCanExit = locationTemplate._aiCanExit;
			this._ownerComplex = ownerComplex;
			this._characterList = new List<LocationCharacter>();
			this._sceneNames = new string[4];
			this.IsInitialized = true;
			for (int i = 0; i < 4; i++)
			{
				this._sceneNames[i] = locationTemplate._sceneNames[i];
			}
		}

		// Token: 0x06003348 RID: 13128 RVA: 0x000D5169 File Offset: 0x000D3369
		public bool CanAIExit(LocationCharacter character)
		{
			if (this._aiCanExitDelegate == null)
			{
				this._aiCanExitDelegate = this.DeserializeDelegate(this._aiCanExit);
			}
			return this._aiCanExitDelegate(character, this);
		}

		// Token: 0x06003349 RID: 13129 RVA: 0x000D5192 File Offset: 0x000D3392
		public bool CanAIEnter(LocationCharacter character)
		{
			if (this._aiCanEnterDelegate == null)
			{
				this._aiCanEnterDelegate = this.DeserializeDelegate(this._aiCanEnter);
			}
			return this._aiCanEnterDelegate(character, this);
		}

		// Token: 0x0600334A RID: 13130 RVA: 0x000D51BB File Offset: 0x000D33BB
		public bool CanPlayerEnter()
		{
			if (this._playerCanEnterDelegate == null)
			{
				this._playerCanEnterDelegate = this.DeserializeDelegate(this._playerCanEnter);
			}
			return this._playerCanEnterDelegate(null, this);
		}

		// Token: 0x0600334B RID: 13131 RVA: 0x000D51E4 File Offset: 0x000D33E4
		public bool CanPlayerSee()
		{
			if (this._playerCanSeeDelegate == null)
			{
				this._playerCanSeeDelegate = this.DeserializeDelegate(this._playerCanSee);
			}
			return this._playerCanSeeDelegate(null, this);
		}

		// Token: 0x0600334C RID: 13132 RVA: 0x000D520D File Offset: 0x000D340D
		public void ReserveLocation(TextObject locationName, TextObject doorName)
		{
			if (this.CanBeReserved)
			{
				this.IsReserved = true;
				this._overriddenName = locationName;
				this._overriddenDoorName = doorName;
			}
		}

		// Token: 0x0600334D RID: 13133 RVA: 0x000D522C File Offset: 0x000D342C
		public void RemoveReservation()
		{
			if (this.CanBeReserved)
			{
				this.IsReserved = false;
				this._overriddenName = TextObject.Empty;
				this._overriddenDoorName = TextObject.Empty;
			}
		}

		// Token: 0x0600334E RID: 13134 RVA: 0x000D5253 File Offset: 0x000D3453
		public void SetOwnerComplex(LocationComplex locationComplex)
		{
			this._ownerComplex = locationComplex;
		}

		// Token: 0x0600334F RID: 13135 RVA: 0x000D525C File Offset: 0x000D345C
		public void AddCharacter(LocationCharacter locationCharacter)
		{
			if (this._characterList == null)
			{
				this._characterList = new List<LocationCharacter>();
			}
			if (locationCharacter.Character.IsHero)
			{
				this._ownerComplex.RemoveCharacterIfExists(locationCharacter.Character.HeroObject);
			}
			this._characterList.Add(locationCharacter);
		}

		// Token: 0x06003350 RID: 13136 RVA: 0x000D52AC File Offset: 0x000D34AC
		public void AddLocationCharacters(CreateLocationCharacterDelegate createDelegate, CultureObject culture, LocationCharacter.CharacterRelations relation, int count)
		{
			for (int i = 0; i < count; i++)
			{
				LocationCharacter locationCharacter = createDelegate(culture, relation);
				this.AddCharacter(locationCharacter);
			}
		}

		// Token: 0x06003351 RID: 13137 RVA: 0x000D52D6 File Offset: 0x000D34D6
		public void AddSpecialItem(ItemObject itemObject)
		{
			this.SpecialItems.Add(itemObject);
		}

		// Token: 0x06003352 RID: 13138 RVA: 0x000D52E4 File Offset: 0x000D34E4
		public string GetSceneName(int upgradeLevel)
		{
			string text = this._sceneNames[upgradeLevel];
			if (string.IsNullOrEmpty(text))
			{
				text = this._sceneNames[0];
			}
			return text;
		}

		// Token: 0x06003353 RID: 13139 RVA: 0x000D530C File Offset: 0x000D350C
		public void SetSceneName(int upgradeLevel, string sceneName)
		{
			this._sceneNames[upgradeLevel] = sceneName;
		}

		// Token: 0x06003354 RID: 13140 RVA: 0x000D5318 File Offset: 0x000D3518
		public int GetSceneCount()
		{
			int num = 0;
			string[] sceneNames = this._sceneNames;
			for (int i = 0; i < sceneNames.Length; i++)
			{
				if (!string.IsNullOrEmpty(sceneNames[i]))
				{
					num++;
				}
			}
			return num;
		}

		// Token: 0x06003355 RID: 13141 RVA: 0x000D534B File Offset: 0x000D354B
		public void RemoveAllHeroCharactersFromPrison()
		{
			if (this._characterList == null)
			{
				this._characterList = new List<LocationCharacter>();
			}
			this._characterList.RemoveAll((LocationCharacter x) => x.Character.HeroObject != null && x.Character.HeroObject != Hero.MainHero);
		}

		// Token: 0x06003356 RID: 13142 RVA: 0x000D538B File Offset: 0x000D358B
		public void RemoveAllCharacters()
		{
			if (this._characterList == null)
			{
				this._characterList = new List<LocationCharacter>();
			}
			this._characterList.Clear();
		}

		// Token: 0x06003357 RID: 13143 RVA: 0x000D53AB File Offset: 0x000D35AB
		public void RemoveAllCharacters(Predicate<LocationCharacter> predicate)
		{
			this._characterList.RemoveAll(predicate);
		}

		// Token: 0x06003358 RID: 13144 RVA: 0x000D53BA File Offset: 0x000D35BA
		public void RemoveLocationCharacter(LocationCharacter locationCharacter)
		{
			this._characterList.Remove(locationCharacter);
		}

		// Token: 0x06003359 RID: 13145 RVA: 0x000D53CC File Offset: 0x000D35CC
		public void RemoveCharacter(Hero hero)
		{
			LocationCharacter locationCharacter = this._characterList.First((LocationCharacter x) => x.Character.HeroObject == hero);
			this.RemoveLocationCharacter(locationCharacter);
		}

		// Token: 0x0600335A RID: 13146 RVA: 0x000D5405 File Offset: 0x000D3605
		public bool ContainsCharacter(LocationCharacter locationCharacter)
		{
			return this._characterList.Contains(locationCharacter);
		}

		// Token: 0x0600335B RID: 13147 RVA: 0x000D5414 File Offset: 0x000D3614
		public bool ContainsCharacter(Hero hero)
		{
			return this._characterList != null && this._characterList.Any((LocationCharacter x) => x.Character == hero.CharacterObject);
		}

		// Token: 0x0600335C RID: 13148 RVA: 0x000D544F File Offset: 0x000D364F
		public void AddPassageToLocation(Location passageToLocation)
		{
			this.LocationsOfPassages.Add(passageToLocation);
		}

		// Token: 0x0600335D RID: 13149 RVA: 0x000D545D File Offset: 0x000D365D
		public IEnumerable<LocationCharacter> GetCharacterList()
		{
			if (this._characterList == null)
			{
				this._characterList = new List<LocationCharacter>();
			}
			foreach (LocationCharacter locationCharacter in this._characterList)
			{
				yield return locationCharacter;
			}
			List<LocationCharacter>.Enumerator enumerator = default(List<LocationCharacter>.Enumerator);
			yield break;
			yield break;
		}

		// Token: 0x0600335E RID: 13150 RVA: 0x000D5470 File Offset: 0x000D3670
		public Location GetPassageToLocation(string locationId)
		{
			return this.LocationsOfPassages.FirstOrDefault((Location location) => locationId == location.StringId);
		}

		// Token: 0x0600335F RID: 13151 RVA: 0x000D54A1 File Offset: 0x000D36A1
		public void OnAIChangeLocation(Location previousLocation)
		{
			if (this.IsIndoor && CampaignMission.Current != null && this != CampaignMission.Current.Location && CampaignMission.Current.Mode == MissionMode.Stealth)
			{
				this._playerCanEnterDelegate = new CanUseDoor(LocationComplex.CanNever);
			}
		}

		// Token: 0x06003360 RID: 13152 RVA: 0x000D54E0 File Offset: 0x000D36E0
		public LocationCharacter GetLocationCharacter(Hero hero)
		{
			return this._characterList.Find((LocationCharacter x) => x.Character == hero.CharacterObject);
		}

		// Token: 0x06003361 RID: 13153 RVA: 0x000D5514 File Offset: 0x000D3714
		public LocationCharacter GetLocationCharacter(IAgentOriginBase agentOrigin)
		{
			foreach (LocationCharacter locationCharacter in this._characterList)
			{
				if (locationCharacter.AgentOrigin == agentOrigin)
				{
					return locationCharacter;
				}
			}
			return null;
		}

		// Token: 0x06003362 RID: 13154 RVA: 0x000D5570 File Offset: 0x000D3770
		private CanUseDoor DeserializeDelegate(string text)
		{
			int num = text.LastIndexOf('.');
			string name = (num >= 0) ? text.Substring(0, num) : typeof(LocationComplex).FullName;
			string name2 = text.Substring(num + 1, text.Length - 1 - num);
			CanUseDoor result = null;
			Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
			for (int i = 0; i < assemblies.Length; i++)
			{
				Type type = assemblies[i].GetType(name);
				if (type != null)
				{
					MethodInfo method = type.GetMethod(name2);
					if (method != null)
					{
						result = (Delegate.CreateDelegate(typeof(CanUseDoor), null, method) as CanUseDoor);
						break;
					}
				}
			}
			return result;
		}

		// Token: 0x04001086 RID: 4230
		[SaveableField(40)]
		private TextObject _overriddenName;

		// Token: 0x04001087 RID: 4231
		[SaveableField(50)]
		private TextObject _overriddenDoorName;

		// Token: 0x04001088 RID: 4232
		private List<LocationCharacter> _characterList;

		// Token: 0x04001089 RID: 4233
		private LocationComplex _ownerComplex;

		// Token: 0x0400108B RID: 4235
		private TextObject _name;

		// Token: 0x0400108C RID: 4236
		private TextObject _doorName;

		// Token: 0x0400108F RID: 4239
		public int ProsperityMax;

		// Token: 0x04001090 RID: 4240
		private string[] _sceneNames;

		// Token: 0x04001091 RID: 4241
		private string _aiCanExit;

		// Token: 0x04001092 RID: 4242
		private string _aiCanEnter;

		// Token: 0x04001093 RID: 4243
		private string _playerCanEnter;

		// Token: 0x04001094 RID: 4244
		private string _playerCanSee;

		// Token: 0x04001095 RID: 4245
		private CanUseDoor _aiCanExitDelegate;

		// Token: 0x04001096 RID: 4246
		private CanUseDoor _aiCanEnterDelegate;

		// Token: 0x04001097 RID: 4247
		private CanUseDoor _playerCanEnterDelegate;

		// Token: 0x04001098 RID: 4248
		private CanUseDoor _playerCanSeeDelegate;
	}
}
