using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.ViewModelCollection.FaceGenerator;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x02000009 RID: 9
	public class FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_3_FaceGenFace__DependendPrefab : Widget
	{
		// Token: 0x06000364 RID: 868 RVA: 0x0001C223 File Offset: 0x0001A423
		public FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_3_FaceGenFace__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x06000365 RID: 869 RVA: 0x0001C22C File Offset: 0x0001A42C
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ScrollablePanel(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new NavigationScopeTargeter(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_1 = new ListPanel(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_1);
			this._widget_0_0_1_0 = new ListPanel(base.Context);
			this._widget_0_0_1.AddChild(this._widget_0_0_1_0);
			this._widget_0_0_1_0_0 = new TextWidget(base.Context);
			this._widget_0_0_1_0.AddChild(this._widget_0_0_1_0_0);
			this._widget_0_0_1_0_1 = new NavigationScopeTargeter(base.Context);
			this._widget_0_0_1_0.AddChild(this._widget_0_0_1_0_1);
			this._widget_0_0_1_0_2 = new NumericUpDownWidget(base.Context);
			this._widget_0_0_1_0.AddChild(this._widget_0_0_1_0_2);
			this._widget_0_0_1_0_2_0 = new NavigationAutoScrollWidget(base.Context);
			this._widget_0_0_1_0_2.AddChild(this._widget_0_0_1_0_2_0);
			this._widget_0_0_1_0_2_1 = new NavigationAutoScrollWidget(base.Context);
			this._widget_0_0_1_0_2.AddChild(this._widget_0_0_1_0_2_1);
			this._widget_0_0_1_0_2_2 = new ButtonWidget(base.Context);
			this._widget_0_0_1_0_2.AddChild(this._widget_0_0_1_0_2_2);
			this._widget_0_0_1_0_2_3 = new Widget(base.Context);
			this._widget_0_0_1_0_2.AddChild(this._widget_0_0_1_0_2_3);
			this._widget_0_0_1_0_2_3_0 = new TextWidget(base.Context);
			this._widget_0_0_1_0_2_3.AddChild(this._widget_0_0_1_0_2_3_0);
			this._widget_0_0_1_0_2_4 = new ButtonWidget(base.Context);
			this._widget_0_0_1_0_2.AddChild(this._widget_0_0_1_0_2_4);
			this._widget_0_0_1_1 = new NavigatableListPanel(base.Context);
			this._widget_0_0_1.AddChild(this._widget_0_0_1_1);
			this._widget_0_1 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_1 = new ScrollbarWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_1 = new ImageWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
		}

		// Token: 0x06000366 RID: 870 RVA: 0x0001C4E8 File Offset: 0x0001A6E8
		public void SetIds()
		{
			this._widget_0_0.Id = "ClipRect";
			this._widget_0_0_1.Id = "InnerList";
			this._widget_0_0_1_0_2.Id = "FaceTypeSelection";
			this._widget_0_0_1_0_2_2.Id = "NumericDown";
			this._widget_0_0_1_0_2_3.Id = "TextContainer";
			this._widget_0_0_1_0_2_3_0.Id = "NumericText";
			this._widget_0_0_1_0_2_4.Id = "NumericUp";
			this._widget_1.Id = "VerticalScrollbar";
			this._widget_1_1.Id = "VerticalScrollbarHandle";
		}

		// Token: 0x06000367 RID: 871 RVA: 0x0001C588 File Offset: 0x0001A788
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			base.MarginTop = 0f;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.AutoHideScrollBars = true;
			this._widget_0.ClipRect = this._widget_0_0;
			this._widget_0.InnerPanel = this._widget_0_0_1;
			this._widget_0.VerticalScrollbar = this._widget_1;
			this._widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0.ClipContents = true;
			this._widget_0_0_0.ScopeID = "FaceScope";
			this._widget_0_0_0.ScopeParent = this._widget_0_0_1;
			this._widget_0_0_0.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_0_0_0.HasCircularMovement = true;
			this._widget_0_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_0_0_1_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0.SuggestedHeight = 60f;
			this._widget_0_0_1_0.MarginTop = 25f;
			this._widget_0_0_1_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0_0.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_0_1_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_1_0_0.MarginRight = 15f;
			this._widget_0_0_1_0_0.Brush = base.Context.GetBrush("FaceGen.Property.Text");
			this._widget_0_0_1_0_1.ScopeID = "FaceTypeSelectionScope";
			this._widget_0_0_1_0_1.ScopeParent = this._widget_0_0_1_0_2;
			this._widget_0_0_1_0_1.ScopeMovements = GamepadNavigationTypes.Horizontal;
			this._widget_0_0_1_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2.SuggestedWidth = 145f;
			this._widget_0_0_1_0_2.SuggestedHeight = 60f;
			this._widget_0_0_1_0_2.DownButton = this._widget_0_0_1_0_2_2;
			this._widget_0_0_1_0_2.ShowOneAdded = true;
			this._widget_0_0_1_0_2.TextWidget = this._widget_0_0_1_0_2_3_0;
			this._widget_0_0_1_0_2.UpButton = this._widget_0_0_1_0_2_4;
			this._widget_0_0_1_0_2_0.TrackedWidget = this._widget_0_0_1_0_2_2;
			this._widget_0_0_1_0_2_0.ScrollYOffset = 50;
			this._widget_0_0_1_0_2_1.TrackedWidget = this._widget_0_0_1_0_2_4;
			this._widget_0_0_1_0_2_1.ScrollYOffset = 50;
			this._widget_0_0_1_0_2_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_2.SuggestedWidth = 29f;
			this._widget_0_0_1_0_2_2.SuggestedHeight = 32f;
			this._widget_0_0_1_0_2_2.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_0_1_0_2_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_1_0_2_2.Brush = base.Context.GetBrush("Creation.NumericLeftArrow");
			this._widget_0_0_1_0_2_2.GamepadNavigationIndex = 0;
			this._widget_0_0_1_0_2_3.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_3.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_3.SuggestedWidth = 74f;
			this._widget_0_0_1_0_2_3.SuggestedHeight = 34f;
			this._widget_0_0_1_0_2_3.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1_0_2_3.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_1_0_2_3.Sprite = base.Context.SpriteData.GetSprite("switcher_9");
			this._widget_0_0_1_0_2_3_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0_2_3_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_0_2_3_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1_0_2_3_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_1_0_2_3_0.Brush = base.Context.GetBrush("FaceGen.Property.Text");
			this._widget_0_0_1_0_2_4.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_4.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0_1_0_2_4.SuggestedWidth = 29f;
			this._widget_0_0_1_0_2_4.SuggestedHeight = 32f;
			this._widget_0_0_1_0_2_4.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_0_1_0_2_4.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0_1_0_2_4.Brush = base.Context.GetBrush("Creation.NumericRightArrow");
			this._widget_0_0_1_0_2_4.GamepadNavigationIndex = 1;
			this._widget_0_0_1_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_1.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_0_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_0_1_1.MarginRight = 10f;
			this._widget_0_0_1_1.MarginTop = 10f;
			this._widget_0_0_1_1.MarginBottom = 80f;
			this._widget_0_0_1_1.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_0_0_1_1.MinIndex = 2000;
			this._widget_0_0_1_1.MaxIndex = 10000;
			this._widget_0_1.DoNotAcceptEvents = true;
			this._widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1.SuggestedWidth = 576f;
			this._widget_0_1.SuggestedHeight = 57f;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_1.VerticalFlip = true;
			this._widget_0_1.Sprite = base.Context.SpriteData.GetSprite("General\\CharacterCreation\\character_creation_scroll_gradient");
			this._widget_0_2.DoNotAcceptEvents = true;
			this._widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.SuggestedWidth = 576f;
			this._widget_0_2.SuggestedHeight = 57f;
			this._widget_0_2.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_2.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_2.Sprite = base.Context.SpriteData.GetSprite("General\\CharacterCreation\\character_creation_scroll_gradient");
			this._widget_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1.SuggestedWidth = 8f;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1.MarginTop = 15f;
			this._widget_1.MarginBottom = 15f;
			this._widget_1.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_1.Handle = this._widget_1_1;
			this._widget_1.MaxValue = 100f;
			this._widget_1.MinValue = 0f;
			this._widget_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.SuggestedWidth = 4f;
			this._widget_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_1_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_1_0.AlphaFactor = 0.2f;
			this._widget_1_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_1.SuggestedHeight = 10f;
			this._widget_1_1.SuggestedWidth = 8f;
			this._widget_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
		}

		// Token: 0x06000368 RID: 872 RVA: 0x0001CCC4 File Offset: 0x0001AEC4
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_FaceTypes != null)
				{
					this._datasource_Root_FaceTypes.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes;
					this._widget_0_0_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._datasource_Root_FaceTypes = null;
				}
				if (this._datasource_Root_FaceProperties != null)
				{
					this._datasource_Root_FaceProperties.ListChanged -= this.OnList_datasource_Root_FacePropertiesChanged;
					for (int i = this._widget_0_0_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_1_1.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)this._widget_0_0_1_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_FaceProperties = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000369 RID: 873 RVA: 0x0001D09E File Offset: 0x0001B29E
		public void SetDataSource(FaceGenVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x0600036A RID: 874 RVA: 0x0001D0A7 File Offset: 0x0001B2A7
		private void PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x0600036B RID: 875 RVA: 0x0001D0B0 File Offset: 0x0001B2B0
		private void boolPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x0600036C RID: 876 RVA: 0x0001D0B9 File Offset: 0x0001B2B9
		private void floatPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x0600036D RID: 877 RVA: 0x0001D0C2 File Offset: 0x0001B2C2
		private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x0600036E RID: 878 RVA: 0x0001D0CB File Offset: 0x0001B2CB
		private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x0600036F RID: 879 RVA: 0x0001D0D4 File Offset: 0x0001B2D4
		private void doublePropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x06000370 RID: 880 RVA: 0x0001D0DD File Offset: 0x0001B2DD
		private void intPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x06000371 RID: 881 RVA: 0x0001D0E6 File Offset: 0x0001B2E6
		private void uintPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x06000372 RID: 882 RVA: 0x0001D0EF File Offset: 0x0001B2EF
		private void ColorPropertyChangedListenerOf_widget_0_0_1_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(propertyName);
		}

		// Token: 0x06000373 RID: 883 RVA: 0x0001D0F8 File Offset: 0x0001B2F8
		private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root_FaceTypes.Name = this._widget_0_0_1_0_0.Text;
				return;
			}
		}

		// Token: 0x06000374 RID: 884 RVA: 0x0001D11E File Offset: 0x0001B31E
		private void PropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x06000375 RID: 885 RVA: 0x0001D127 File Offset: 0x0001B327
		private void boolPropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x06000376 RID: 886 RVA: 0x0001D130 File Offset: 0x0001B330
		private void floatPropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x06000377 RID: 887 RVA: 0x0001D139 File Offset: 0x0001B339
		private void Vec2PropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x06000378 RID: 888 RVA: 0x0001D142 File Offset: 0x0001B342
		private void Vector2PropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x06000379 RID: 889 RVA: 0x0001D14B File Offset: 0x0001B34B
		private void doublePropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x0600037A RID: 890 RVA: 0x0001D154 File Offset: 0x0001B354
		private void intPropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x0600037B RID: 891 RVA: 0x0001D15D File Offset: 0x0001B35D
		private void uintPropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x0600037C RID: 892 RVA: 0x0001D166 File Offset: 0x0001B366
		private void ColorPropertyChangedListenerOf_widget_0_0_1_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(propertyName);
		}

		// Token: 0x0600037D RID: 893 RVA: 0x0001D170 File Offset: 0x0001B370
		private void HandleWidgetPropertyChangeOf_widget_0_0_1_0_2(string propertyName)
		{
			if (propertyName == "MaxValue")
			{
				this._datasource_Root_FaceTypes.Max = this._widget_0_0_1_0_2.MaxValue;
				return;
			}
			if (propertyName == "MinValue")
			{
				this._datasource_Root_FaceTypes.Min = this._widget_0_0_1_0_2.MinValue;
				return;
			}
			if (propertyName == "Value")
			{
				this._datasource_Root_FaceTypes.Value = this._widget_0_0_1_0_2.Value;
				return;
			}
		}

		// Token: 0x0600037E RID: 894 RVA: 0x0001D1E9 File Offset: 0x0001B3E9
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600037F RID: 895 RVA: 0x0001D1F7 File Offset: 0x0001B3F7
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000380 RID: 896 RVA: 0x0001D205 File Offset: 0x0001B405
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000381 RID: 897 RVA: 0x0001D213 File Offset: 0x0001B413
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000382 RID: 898 RVA: 0x0001D221 File Offset: 0x0001B421
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000383 RID: 899 RVA: 0x0001D22F File Offset: 0x0001B42F
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000384 RID: 900 RVA: 0x0001D23D File Offset: 0x0001B43D
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000385 RID: 901 RVA: 0x0001D24B File Offset: 0x0001B44B
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000386 RID: 902 RVA: 0x0001D259 File Offset: 0x0001B459
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000387 RID: 903 RVA: 0x0001D267 File Offset: 0x0001B467
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "FaceTypes")
			{
				this.RefreshDataSource_datasource_Root_FaceTypes(this._datasource_Root.FaceTypes);
				return;
			}
			if (propertyName == "FaceProperties")
			{
				this.RefreshDataSource_datasource_Root_FaceProperties(this._datasource_Root.FaceProperties);
				return;
			}
		}

		// Token: 0x06000388 RID: 904 RVA: 0x0001D2A7 File Offset: 0x0001B4A7
		private void ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x06000389 RID: 905 RVA: 0x0001D2B5 File Offset: 0x0001B4B5
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038A RID: 906 RVA: 0x0001D2C3 File Offset: 0x0001B4C3
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038B RID: 907 RVA: 0x0001D2D1 File Offset: 0x0001B4D1
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038C RID: 908 RVA: 0x0001D2DF File Offset: 0x0001B4DF
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038D RID: 909 RVA: 0x0001D2ED File Offset: 0x0001B4ED
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038E RID: 910 RVA: 0x0001D2FB File Offset: 0x0001B4FB
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x0600038F RID: 911 RVA: 0x0001D309 File Offset: 0x0001B509
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x06000390 RID: 912 RVA: 0x0001D317 File Offset: 0x0001B517
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(e.PropertyName);
		}

		// Token: 0x06000391 RID: 913 RVA: 0x0001D328 File Offset: 0x0001B528
		private void HandleViewModelPropertyChangeOf_datasource_Root_FaceTypes(string propertyName)
		{
			if (propertyName == "Name")
			{
				this._widget_0_0_1_0_0.Text = this._datasource_Root_FaceTypes.Name;
				return;
			}
			if (propertyName == "Max")
			{
				this._widget_0_0_1_0_2.MaxValue = this._datasource_Root_FaceTypes.Max;
				return;
			}
			if (propertyName == "Min")
			{
				this._widget_0_0_1_0_2.MinValue = this._datasource_Root_FaceTypes.Min;
				return;
			}
			if (propertyName == "Value")
			{
				this._widget_0_0_1_0_2.Value = this._datasource_Root_FaceTypes.Value;
				return;
			}
		}

		// Token: 0x06000392 RID: 914 RVA: 0x0001D3C8 File Offset: 0x0001B5C8
		public void OnList_datasource_Root_FacePropertiesChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
				for (int i = this._widget_0_0_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_1_1.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_1_1.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_1_1.RemoveChild(child2);
				}
				return;
			case ListChangedType.Sorted:
				for (int j = 0; j < this._datasource_Root_FaceProperties.Count; j++)
				{
					FaceGenPropertyVM bindingObject = this._datasource_Root_FaceProperties[j];
					this._widget_0_0_1_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case ListChangedType.ItemAdded:
			{
				FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate);
				FaceGenPropertyVM faceGenPropertyVM = this._datasource_Root_FaceProperties[e.NewIndex];
				generatedWidgetData.Data = faceGenPropertyVM;
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_0_1_1.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate, e.NewIndex);
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.CreateWidgets();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetIds();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetAttributes();
				faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetDataSource(faceGenPropertyVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_0_1_1.GetChild(e.NewIndex);
				((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_0_1_1.GetChild(e.NewIndex);
				((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_0_1_1.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000393 RID: 915 RVA: 0x0001D564 File Offset: 0x0001B764
		private void RefreshDataSource_datasource_Root(FaceGenVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				if (this._datasource_Root_FaceTypes != null)
				{
					this._datasource_Root_FaceTypes.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes;
					this._widget_0_0_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._datasource_Root_FaceTypes = null;
				}
				if (this._datasource_Root_FaceProperties != null)
				{
					this._datasource_Root_FaceProperties.ListChanged -= this.OnList_datasource_Root_FacePropertiesChanged;
					for (int i = this._widget_0_0_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_1_1.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_0_1_1.GetChild(i);
						((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_0_1_1.RemoveChild(child2);
					}
					this._datasource_Root_FaceProperties = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root_FaceTypes = this._datasource_Root.FaceTypes;
				if (this._datasource_Root_FaceTypes != null)
				{
					this._datasource_Root_FaceTypes.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes;
					this._datasource_Root_FaceTypes.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes;
					this._widget_0_0_1_0_0.Text = this._datasource_Root_FaceTypes.Name;
					this._widget_0_0_1_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1_0_0;
					this._widget_0_0_1_0_2.MaxValue = this._datasource_Root_FaceTypes.Max;
					this._widget_0_0_1_0_2.MinValue = this._datasource_Root_FaceTypes.Min;
					this._widget_0_0_1_0_2.Value = this._datasource_Root_FaceTypes.Value;
					this._widget_0_0_1_0_2.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1_0_2;
					this._widget_0_0_1_0_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1_0_2;
				}
				this._datasource_Root_FaceProperties = this._datasource_Root.FaceProperties;
				if (this._datasource_Root_FaceProperties != null)
				{
					this._datasource_Root_FaceProperties.ListChanged += this.OnList_datasource_Root_FacePropertiesChanged;
					for (int j = 0; j < this._datasource_Root_FaceProperties.Count; j++)
					{
						FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate);
						FaceGenPropertyVM faceGenPropertyVM = this._datasource_Root_FaceProperties[j];
						generatedWidgetData.Data = faceGenPropertyVM;
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_0_1_1.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate, j);
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.CreateWidgets();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetIds();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetAttributes();
						faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetDataSource(faceGenPropertyVM);
					}
				}
			}
		}

		// Token: 0x06000394 RID: 916 RVA: 0x0001DDBC File Offset: 0x0001BFBC
		private void RefreshDataSource_datasource_Root_FaceTypes(FaceGenPropertyVM newDataSource)
		{
			if (this._datasource_Root_FaceTypes != null)
			{
				this._datasource_Root_FaceTypes.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes;
				this._widget_0_0_1_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._datasource_Root_FaceTypes = null;
			}
			this._datasource_Root_FaceTypes = newDataSource;
			this._datasource_Root_FaceTypes = this._datasource_Root.FaceTypes;
			if (this._datasource_Root_FaceTypes != null)
			{
				this._datasource_Root_FaceTypes.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_FaceTypes;
				this._datasource_Root_FaceTypes.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_FaceTypes;
				this._widget_0_0_1_0_0.Text = this._datasource_Root_FaceTypes.Name;
				this._widget_0_0_1_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1_0_0;
				this._widget_0_0_1_0_2.MaxValue = this._datasource_Root_FaceTypes.Max;
				this._widget_0_0_1_0_2.MinValue = this._datasource_Root_FaceTypes.Min;
				this._widget_0_0_1_0_2.Value = this._datasource_Root_FaceTypes.Value;
				this._widget_0_0_1_0_2.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_1_0_2;
				this._widget_0_0_1_0_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_1_0_2;
			}
		}

		// Token: 0x06000395 RID: 917 RVA: 0x0001E330 File Offset: 0x0001C530
		private void RefreshDataSource_datasource_Root_FaceProperties(MBBindingList<FaceGenPropertyVM> newDataSource)
		{
			if (this._datasource_Root_FaceProperties != null)
			{
				this._datasource_Root_FaceProperties.ListChanged -= this.OnList_datasource_Root_FacePropertiesChanged;
				for (int i = this._widget_0_0_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_1_1.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_1_1.GetChild(i);
					((FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_1_1.RemoveChild(child2);
				}
				this._datasource_Root_FaceProperties = null;
			}
			this._datasource_Root_FaceProperties = newDataSource;
			this._datasource_Root_FaceProperties = this._datasource_Root.FaceProperties;
			if (this._datasource_Root_FaceProperties != null)
			{
				this._datasource_Root_FaceProperties.ListChanged += this.OnList_datasource_Root_FacePropertiesChanged;
				for (int j = 0; j < this._datasource_Root_FaceProperties.Count; j++)
				{
					FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate = new FaceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate);
					FaceGenPropertyVM faceGenPropertyVM = this._datasource_Root_FaceProperties[j];
					generatedWidgetData.Data = faceGenPropertyVM;
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_0_1_1.AddChildAtIndex(faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate, j);
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.CreateWidgets();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetIds();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetAttributes();
					faceGen__TaleWorlds_MountAndBlade_ViewModelCollection_FaceGenerator_FaceGenVM_Dependency_12_ItemTemplate.SetDataSource(faceGenPropertyVM);
				}
			}
		}

		// Token: 0x040000B3 RID: 179
		private Widget _widget;

		// Token: 0x040000B4 RID: 180
		private ScrollablePanel _widget_0;

		// Token: 0x040000B5 RID: 181
		private Widget _widget_0_0;

		// Token: 0x040000B6 RID: 182
		private NavigationScopeTargeter _widget_0_0_0;

		// Token: 0x040000B7 RID: 183
		private ListPanel _widget_0_0_1;

		// Token: 0x040000B8 RID: 184
		private ListPanel _widget_0_0_1_0;

		// Token: 0x040000B9 RID: 185
		private TextWidget _widget_0_0_1_0_0;

		// Token: 0x040000BA RID: 186
		private NavigationScopeTargeter _widget_0_0_1_0_1;

		// Token: 0x040000BB RID: 187
		private NumericUpDownWidget _widget_0_0_1_0_2;

		// Token: 0x040000BC RID: 188
		private NavigationAutoScrollWidget _widget_0_0_1_0_2_0;

		// Token: 0x040000BD RID: 189
		private NavigationAutoScrollWidget _widget_0_0_1_0_2_1;

		// Token: 0x040000BE RID: 190
		private ButtonWidget _widget_0_0_1_0_2_2;

		// Token: 0x040000BF RID: 191
		private Widget _widget_0_0_1_0_2_3;

		// Token: 0x040000C0 RID: 192
		private TextWidget _widget_0_0_1_0_2_3_0;

		// Token: 0x040000C1 RID: 193
		private ButtonWidget _widget_0_0_1_0_2_4;

		// Token: 0x040000C2 RID: 194
		private NavigatableListPanel _widget_0_0_1_1;

		// Token: 0x040000C3 RID: 195
		private Widget _widget_0_1;

		// Token: 0x040000C4 RID: 196
		private Widget _widget_0_2;

		// Token: 0x040000C5 RID: 197
		private ScrollbarWidget _widget_1;

		// Token: 0x040000C6 RID: 198
		private Widget _widget_1_0;

		// Token: 0x040000C7 RID: 199
		private ImageWidget _widget_1_1;

		// Token: 0x040000C8 RID: 200
		private FaceGenVM _datasource_Root;

		// Token: 0x040000C9 RID: 201
		private FaceGenPropertyVM _datasource_Root_FaceTypes;

		// Token: 0x040000CA RID: 202
		private MBBindingList<FaceGenPropertyVM> _datasource_Root_FaceProperties;
	}
}
