using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Barter;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Party;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x0200001F RID: 31
	public class BarterScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Barter_BarterVM_Dependency_25_BarterToggleTuple__DependendPrefab : PartyHeaderToggleWidget
	{
		// Token: 0x06000492 RID: 1170 RVA: 0x00024B99 File Offset: 0x00022D99
		public BarterScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Barter_BarterVM_Dependency_25_BarterToggleTuple__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x06000493 RID: 1171 RVA: 0x00024BA4 File Offset: 0x00022DA4
		private VisualDefinition CreateVisualDefinitionToggle()
		{
			VisualDefinition visualDefinition = new VisualDefinition("Toggle", 0.045f, 0f, false);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedWidth = 465f
			});
			visualDefinition.AddVisualState(new VisualState("Pressed")
			{
				SuggestedWidth = 465f
			});
			visualDefinition.AddVisualState(new VisualState("Selected")
			{
				SuggestedWidth = 465f
			});
			visualDefinition.AddVisualState(new VisualState("Hovered")
			{
				SuggestedWidth = 465f
			});
			return visualDefinition;
		}

		// Token: 0x06000494 RID: 1172 RVA: 0x00024C3C File Offset: 0x00022E3C
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new ListPanel(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new BrushWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_1 = new RichTextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_2 = new RichTextWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_1 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new HintWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
		}

		// Token: 0x06000495 RID: 1173 RVA: 0x00024D1C File Offset: 0x00022F1C
		public void SetIds()
		{
			this._widget_0.Id = "Description";
			this._widget_0_0.Id = "CollapseIndicator";
			this._widget_1.Id = "TransferAll";
		}

		// Token: 0x06000496 RID: 1174 RVA: 0x00024D50 File Offset: 0x00022F50
		public void SetAttributes()
		{
			base.VisualDefinition = this.CreateVisualDefinitionToggle();
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedWidth = 465f;
			base.SuggestedHeight = 73f;
			base.VerticalAlignment = VerticalAlignment.Top;
			base.MarginTop = 4f;
			base.Brush = base.Context.GetBrush("Barter.RightPanel.Toggle");
			base.CollapseIndicator = this._widget_0_0;
			base.UpdateChildrenStates = true;
			this._widget_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.MarginBottom = 10f;
			this._widget_0.IsDisabled = true;
			this._widget_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0.UpdateChildrenStates = true;
			this._widget_0.DoNotPassEventsToChildren = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 40f;
			this._widget_0_0.SuggestedHeight = 40f;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.PositionYOffset = 5f;
			this._widget_0_0.MarginRight = 5f;
			this._widget_0_0.Brush = base.Context.GetBrush("Party.Toggle.ExpandIndicator");
			this._widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_1.MarginRight = 5f;
			this._widget_0_1.Brush = base.Context.GetBrush("Party.Text.Toggle");
			this._widget_0_2.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_2.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_2.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_2.MarginLeft = 5f;
			this._widget_0_2.Brush = base.Context.GetBrush("Party.Text.Toggle");
			this._widget_0_2.Text = "";
			this._widget_1.DoNotPassEventsToChildren = true;
			this._widget_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1.SuggestedWidth = 42f;
			this._widget_1.SuggestedHeight = 42f;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1.MarginRight = 5f;
			this._widget_1.MarginLeft = 5f;
			this._widget_1.Brush = base.Context.GetBrush("ButtonRightDoubleArrowBrush1");
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.IsDisabled = true;
		}

		// Token: 0x06000497 RID: 1175 RVA: 0x00025040 File Offset: 0x00023240
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._widget_1_0.EventFire -= this.EventListenerOf_widget_1_0;
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000498 RID: 1176 RVA: 0x00025242 File Offset: 0x00023442
		public void SetDataSource(BarterVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000499 RID: 1177 RVA: 0x0002524B File Offset: 0x0002344B
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			commandName == "Drop";
		}

		// Token: 0x0600049A RID: 1178 RVA: 0x00025259 File Offset: 0x00023459
		private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
		{
			commandName == "Click";
		}

		// Token: 0x0600049B RID: 1179 RVA: 0x00025267 File Offset: 0x00023467
		private void EventListenerOf_widget_1_0(Widget widget, string commandName, object[] args)
		{
			commandName == "HoverBegin";
			commandName == "HoverEnd";
		}

		// Token: 0x0600049C RID: 1180 RVA: 0x00025281 File Offset: 0x00023481
		private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600049D RID: 1181 RVA: 0x0002528A File Offset: 0x0002348A
		private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600049E RID: 1182 RVA: 0x00025293 File Offset: 0x00023493
		private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x0600049F RID: 1183 RVA: 0x0002529C File Offset: 0x0002349C
		private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A0 RID: 1184 RVA: 0x000252A5 File Offset: 0x000234A5
		private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A1 RID: 1185 RVA: 0x000252AE File Offset: 0x000234AE
		private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A2 RID: 1186 RVA: 0x000252B7 File Offset: 0x000234B7
		private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A3 RID: 1187 RVA: 0x000252C0 File Offset: 0x000234C0
		private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A4 RID: 1188 RVA: 0x000252C9 File Offset: 0x000234C9
		private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
		}

		// Token: 0x060004A5 RID: 1189 RVA: 0x000252D2 File Offset: 0x000234D2
		private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.DiplomaticLbl = this._widget_0_1.Text;
				return;
			}
		}

		// Token: 0x060004A6 RID: 1190 RVA: 0x000252F8 File Offset: 0x000234F8
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004A7 RID: 1191 RVA: 0x00025306 File Offset: 0x00023506
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004A8 RID: 1192 RVA: 0x00025314 File Offset: 0x00023514
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004A9 RID: 1193 RVA: 0x00025322 File Offset: 0x00023522
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AA RID: 1194 RVA: 0x00025330 File Offset: 0x00023530
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AB RID: 1195 RVA: 0x0002533E File Offset: 0x0002353E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AC RID: 1196 RVA: 0x0002534C File Offset: 0x0002354C
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AD RID: 1197 RVA: 0x0002535A File Offset: 0x0002355A
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AE RID: 1198 RVA: 0x00025368 File Offset: 0x00023568
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060004AF RID: 1199 RVA: 0x00025376 File Offset: 0x00023576
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "DiplomaticLbl")
			{
				this._widget_0_1.Text = this._datasource_Root.DiplomaticLbl;
				return;
			}
		}

		// Token: 0x060004B0 RID: 1200 RVA: 0x0002539C File Offset: 0x0002359C
		private void RefreshDataSource_datasource_Root(BarterVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._widget_1_0.EventFire -= this.EventListenerOf_widget_1_0;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget_0_1.Text = this._datasource_Root.DiplomaticLbl;
				this._widget_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_1;
				this._widget_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_1;
				this._widget_1.EventFire += this.EventListenerOf_widget_1;
				this._widget_1_0.EventFire += this.EventListenerOf_widget_1_0;
			}
		}

		// Token: 0x0400011A RID: 282
		private PartyHeaderToggleWidget _widget;

		// Token: 0x0400011B RID: 283
		private ListPanel _widget_0;

		// Token: 0x0400011C RID: 284
		private BrushWidget _widget_0_0;

		// Token: 0x0400011D RID: 285
		private RichTextWidget _widget_0_1;

		// Token: 0x0400011E RID: 286
		private RichTextWidget _widget_0_2;

		// Token: 0x0400011F RID: 287
		private ButtonWidget _widget_1;

		// Token: 0x04000120 RID: 288
		private HintWidget _widget_1_0;

		// Token: 0x04000121 RID: 289
		private BarterVM _datasource_Root;
	}
}
