using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.WeaponCrafting.Refinement;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000085 RID: 133
	public class Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_11_RefinementCategory__DependendPrefab : Widget
	{
		// Token: 0x060029A9 RID: 10665 RVA: 0x00157073 File Offset: 0x00155273
		public Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_11_RefinementCategory__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x060029AA RID: 10666 RVA: 0x0015707C File Offset: 0x0015527C
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new TextWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_1 = new ListPanel(base.Context);
			this._widget_0.AddChild(this._widget_0_1);
			this._widget_0_1_0 = new ScrollablePanel(base.Context);
			this._widget_0_1.AddChild(this._widget_0_1_0);
			this._widget_0_1_0_0 = new NavigationScopeTargeter(base.Context);
			this._widget_0_1_0.AddChild(this._widget_0_1_0_0);
			this._widget_0_1_0_1 = new Widget(base.Context);
			this._widget_0_1_0.AddChild(this._widget_0_1_0_1);
			this._widget_0_1_0_1_0 = new NavigatableListPanel(base.Context);
			this._widget_0_1_0_1.AddChild(this._widget_0_1_0_1_0);
			this._widget_0_1_0_1_1 = new Widget(base.Context);
			this._widget_0_1_0_1.AddChild(this._widget_0_1_0_1_1);
			this._widget_0_2 = new ScrollbarWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_2);
			this._widget_0_2_0 = new Widget(base.Context);
			this._widget_0_2.AddChild(this._widget_0_2_0);
			this._widget_0_2_1 = new ImageWidget(base.Context);
			this._widget_0_2.AddChild(this._widget_0_2_1);
		}

		// Token: 0x060029AB RID: 10667 RVA: 0x00157228 File Offset: 0x00155428
		public void SetIds()
		{
			base.Id = "RefinementCategoryParent";
			this._widget_0.Id = "InnerPanel";
			this._widget_0_1_0_1.Id = "ClipRect";
			this._widget_0_1_0_1_0.Id = "RefinementActionsList";
			this._widget_0_2.Id = "VerticalScrollbar";
			this._widget_0_2_1.Id = "VerticalScrollbarHandle";
		}

		// Token: 0x060029AC RID: 10668 RVA: 0x00157290 File Offset: 0x00155490
		public void SetAttributes()
		{
			base.DoNotAcceptEvents = true;
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0.SuggestedWidth = 585f;
			this._widget_0.SuggestedHeight = 770f;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.MarginTop = 10f;
			this._widget_0.PositionXOffset = 16f;
			this._widget_0.PositionYOffset = 24f;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 575f;
			this._widget_0_0.SuggestedHeight = 51f;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_0.Sprite = base.Context.SpriteData.GetSprite("Crafting\\refine_panel_header");
			this._widget_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_0_0.Brush = base.Context.GetBrush("Refinement.Tuple.Text");
			this._widget_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
			this._widget_0_1.MarginLeft = 6f;
			this._widget_0_1.MarginTop = 48f;
			this._widget_0_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_1_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0_1_0.AutoHideScrollBars = true;
			this._widget_0_1_0.ClipRect = this._widget_0_1_0_1;
			this._widget_0_1_0.InnerPanel = this._widget_0_1_0_1_0;
			this._widget_0_1_0.VerticalScrollbar = this._widget_0_2;
			this._widget_0_1_0_0.ScopeID = "RefinementScope";
			this._widget_0_1_0_0.ScopeParent = this._widget_0_1_0_1;
			this._widget_0_1_0_0.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_0_1_0_0.HasCircularMovement = true;
			this._widget_0_1_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1_0_1.ClipContents = true;
			this._widget_0_1_0_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_1_0_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0_1_0_1_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_0_1_0_1_0.MarginBottom = 40f;
			this._widget_0_1_0_1_1.DoNotAcceptEvents = true;
			this._widget_0_1_0_1_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_1_0_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_1_0_1_1.SuggestedWidth = 576f;
			this._widget_0_1_0_1_1.SuggestedHeight = 57f;
			this._widget_0_1_0_1_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_1_0_1_1.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_1_0_1_1.IsEnabled = false;
			this._widget_0_1_0_1_1.Sprite = base.Context.SpriteData.GetSprite("General\\CharacterCreation\\character_creation_scroll_gradient");
			this._widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_2.SuggestedWidth = 8f;
			this._widget_0_2.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_0_2.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_0_2.MarginTop = 7f;
			this._widget_0_2.MarginBottom = 7f;
			this._widget_0_2.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_0_2.Handle = this._widget_0_2_1;
			this._widget_0_2.MaxValue = 100f;
			this._widget_0_2.MinValue = 0f;
			this._widget_0_2_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0_2_0.SuggestedWidth = 4f;
			this._widget_0_2_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_2_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0_2_0.AlphaFactor = 0.2f;
			this._widget_0_2_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_0_2_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_2_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_2_1.SuggestedWidth = 8f;
			this._widget_0_2_1.SuggestedHeight = 10f;
			this._widget_0_2_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0_2_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
		}

		// Token: 0x060029AD RID: 10669 RVA: 0x00157724 File Offset: 0x00155924
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0;
				if (this._datasource_Root_AvailableRefinementActions != null)
				{
					this._datasource_Root_AvailableRefinementActions.ListChanged -= this.OnList_datasource_Root_AvailableRefinementActionsChanged;
					for (int i = this._widget_0_1_0_1_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1_0_1_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)this._widget_0_1_0_1_0.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_AvailableRefinementActions = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x060029AE RID: 10670 RVA: 0x0015794E File Offset: 0x00155B4E
		public void SetDataSource(RefinementVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060029AF RID: 10671 RVA: 0x00157957 File Offset: 0x00155B57
		private void PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B0 RID: 10672 RVA: 0x00157960 File Offset: 0x00155B60
		private void boolPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B1 RID: 10673 RVA: 0x00157969 File Offset: 0x00155B69
		private void floatPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B2 RID: 10674 RVA: 0x00157972 File Offset: 0x00155B72
		private void Vec2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B3 RID: 10675 RVA: 0x0015797B File Offset: 0x00155B7B
		private void Vector2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B4 RID: 10676 RVA: 0x00157984 File Offset: 0x00155B84
		private void doublePropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B5 RID: 10677 RVA: 0x0015798D File Offset: 0x00155B8D
		private void intPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B6 RID: 10678 RVA: 0x00157996 File Offset: 0x00155B96
		private void uintPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B7 RID: 10679 RVA: 0x0015799F File Offset: 0x00155B9F
		private void ColorPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
		}

		// Token: 0x060029B8 RID: 10680 RVA: 0x001579A8 File Offset: 0x00155BA8
		private void HandleWidgetPropertyChangeOf_widget_0_0_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.RefinementText = this._widget_0_0_0.Text;
				return;
			}
		}

		// Token: 0x060029B9 RID: 10681 RVA: 0x001579CE File Offset: 0x00155BCE
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BA RID: 10682 RVA: 0x001579DC File Offset: 0x00155BDC
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BB RID: 10683 RVA: 0x001579EA File Offset: 0x00155BEA
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BC RID: 10684 RVA: 0x001579F8 File Offset: 0x00155BF8
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BD RID: 10685 RVA: 0x00157A06 File Offset: 0x00155C06
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BE RID: 10686 RVA: 0x00157A14 File Offset: 0x00155C14
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029BF RID: 10687 RVA: 0x00157A22 File Offset: 0x00155C22
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029C0 RID: 10688 RVA: 0x00157A30 File Offset: 0x00155C30
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029C1 RID: 10689 RVA: 0x00157A3E File Offset: 0x00155C3E
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060029C2 RID: 10690 RVA: 0x00157A4C File Offset: 0x00155C4C
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "AvailableRefinementActions")
			{
				this.RefreshDataSource_datasource_Root_AvailableRefinementActions(this._datasource_Root.AvailableRefinementActions);
				return;
			}
			if (propertyName == "RefinementText")
			{
				this._widget_0_0_0.Text = this._datasource_Root.RefinementText;
				return;
			}
		}

		// Token: 0x060029C3 RID: 10691 RVA: 0x00157A9C File Offset: 0x00155C9C
		public void OnList_datasource_Root_AvailableRefinementActionsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
				for (int i = this._widget_0_1_0_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1_0_1_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1_0_1_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1_0_1_0.RemoveChild(child2);
				}
				return;
			case ListChangedType.Sorted:
				for (int j = 0; j < this._datasource_Root_AvailableRefinementActions.Count; j++)
				{
					RefinementActionItemVM bindingObject = this._datasource_Root_AvailableRefinementActions[j];
					this._widget_0_1_0_1_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case ListChangedType.ItemAdded:
			{
				Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate);
				RefinementActionItemVM refinementActionItemVM = this._datasource_Root_AvailableRefinementActions[e.NewIndex];
				generatedWidgetData.Data = refinementActionItemVM;
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_1_0_1_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate, e.NewIndex);
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.CreateWidgets();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetIds();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetAttributes();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetDataSource(refinementActionItemVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_0_1_0_1_0.GetChild(e.NewIndex);
				((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_0_1_0_1_0.GetChild(e.NewIndex);
				((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_1_0_1_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x060029C4 RID: 10692 RVA: 0x00157C38 File Offset: 0x00155E38
		private void RefreshDataSource_datasource_Root(RefinementVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0_0;
				if (this._datasource_Root_AvailableRefinementActions != null)
				{
					this._datasource_Root_AvailableRefinementActions.ListChanged -= this.OnList_datasource_Root_AvailableRefinementActionsChanged;
					for (int i = this._widget_0_1_0_1_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_1_0_1_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_1_0_1_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_1_0_1_0.RemoveChild(child2);
					}
					this._datasource_Root_AvailableRefinementActions = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_0_0_0.Text = this._datasource_Root.RefinementText;
				this._widget_0_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0_0;
				this._widget_0_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0_0;
				this._datasource_Root_AvailableRefinementActions = this._datasource_Root.AvailableRefinementActions;
				if (this._datasource_Root_AvailableRefinementActions != null)
				{
					this._datasource_Root_AvailableRefinementActions.ListChanged += this.OnList_datasource_Root_AvailableRefinementActionsChanged;
					for (int j = 0; j < this._datasource_Root_AvailableRefinementActions.Count; j++)
					{
						Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate);
						RefinementActionItemVM refinementActionItemVM = this._datasource_Root_AvailableRefinementActions[j];
						generatedWidgetData.Data = refinementActionItemVM;
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_1_0_1_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate, j);
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.CreateWidgets();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetIds();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetAttributes();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetDataSource(refinementActionItemVM);
					}
				}
			}
		}

		// Token: 0x060029C5 RID: 10693 RVA: 0x001580E4 File Offset: 0x001562E4
		private void RefreshDataSource_datasource_Root_AvailableRefinementActions(MBBindingList<RefinementActionItemVM> newDataSource)
		{
			if (this._datasource_Root_AvailableRefinementActions != null)
			{
				this._datasource_Root_AvailableRefinementActions.ListChanged -= this.OnList_datasource_Root_AvailableRefinementActionsChanged;
				for (int i = this._widget_0_1_0_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_1_0_1_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_1_0_1_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_1_0_1_0.RemoveChild(child2);
				}
				this._datasource_Root_AvailableRefinementActions = null;
			}
			this._datasource_Root_AvailableRefinementActions = newDataSource;
			this._datasource_Root_AvailableRefinementActions = this._datasource_Root.AvailableRefinementActions;
			if (this._datasource_Root_AvailableRefinementActions != null)
			{
				this._datasource_Root_AvailableRefinementActions.ListChanged += this.OnList_datasource_Root_AvailableRefinementActionsChanged;
				for (int j = 0; j < this._datasource_Root_AvailableRefinementActions.Count; j++)
				{
					Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate);
					RefinementActionItemVM refinementActionItemVM = this._datasource_Root_AvailableRefinementActions[j];
					generatedWidgetData.Data = refinementActionItemVM;
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_1_0_1_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate, j);
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.CreateWidgets();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetIds();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetAttributes();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_26_ItemTemplate.SetDataSource(refinementActionItemVM);
				}
			}
		}

		// Token: 0x040008B0 RID: 2224
		private Widget _widget;

		// Token: 0x040008B1 RID: 2225
		private Widget _widget_0;

		// Token: 0x040008B2 RID: 2226
		private Widget _widget_0_0;

		// Token: 0x040008B3 RID: 2227
		private TextWidget _widget_0_0_0;

		// Token: 0x040008B4 RID: 2228
		private ListPanel _widget_0_1;

		// Token: 0x040008B5 RID: 2229
		private ScrollablePanel _widget_0_1_0;

		// Token: 0x040008B6 RID: 2230
		private NavigationScopeTargeter _widget_0_1_0_0;

		// Token: 0x040008B7 RID: 2231
		private Widget _widget_0_1_0_1;

		// Token: 0x040008B8 RID: 2232
		private NavigatableListPanel _widget_0_1_0_1_0;

		// Token: 0x040008B9 RID: 2233
		private Widget _widget_0_1_0_1_1;

		// Token: 0x040008BA RID: 2234
		private ScrollbarWidget _widget_0_2;

		// Token: 0x040008BB RID: 2235
		private Widget _widget_0_2_0;

		// Token: 0x040008BC RID: 2236
		private ImageWidget _widget_0_2_1;

		// Token: 0x040008BD RID: 2237
		private RefinementVM _datasource_Root;

		// Token: 0x040008BE RID: 2238
		private MBBindingList<RefinementActionItemVM> _datasource_Root_AvailableRefinementActions;
	}
}
