using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.CampaignSystem.ViewModelCollection.WeaponCrafting.WeaponDesign;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000089 RID: 137
	public class Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_15_CraftingHistoryPopup__DependendPrefab : Widget
	{
		// Token: 0x06002AE0 RID: 10976 RVA: 0x0016409F File Offset: 0x0016229F
		public Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_15_CraftingHistoryPopup__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x06002AE1 RID: 10977 RVA: 0x001640A8 File Offset: 0x001622A8
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new ImageWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_1 = new ImageWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_1_2 = new TextWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_2);
			this._widget_1_3 = new ImageWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_3);
			this._widget_1_4 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_4);
			this._widget_1_4_0 = new ScrollablePanel(base.Context);
			this._widget_1_4.AddChild(this._widget_1_4_0);
			this._widget_1_4_0_0 = new NavigationForcedScopeCollectionTargeter(base.Context);
			this._widget_1_4_0.AddChild(this._widget_1_4_0_0);
			this._widget_1_4_0_1 = new NavigationScopeTargeter(base.Context);
			this._widget_1_4_0.AddChild(this._widget_1_4_0_1);
			this._widget_1_4_0_2 = new Widget(base.Context);
			this._widget_1_4_0.AddChild(this._widget_1_4_0_2);
			this._widget_1_4_0_2_0 = new NavigatableListPanel(base.Context);
			this._widget_1_4_0_2.AddChild(this._widget_1_4_0_2_0);
			this._widget_1_4_1 = new ScrollbarWidget(base.Context);
			this._widget_1_4.AddChild(this._widget_1_4_1);
			this._widget_1_4_1_0 = new Widget(base.Context);
			this._widget_1_4_1.AddChild(this._widget_1_4_1_0);
			this._widget_1_4_1_1 = new ImageWidget(base.Context);
			this._widget_1_4_1.AddChild(this._widget_1_4_1_1);
			this._widget_1_5 = new ListPanel(base.Context);
			this._widget_1.AddChild(this._widget_1_5);
			this._widget_1_5_0 = new ButtonWidget(base.Context);
			this._widget_1_5.AddChild(this._widget_1_5_0);
			this._widget_1_5_0_0 = new InputKeyVisualWidget(base.Context);
			this._widget_1_5_0.AddChild(this._widget_1_5_0_0);
			this._widget_1_5_0_1 = new TextWidget(base.Context);
			this._widget_1_5_0.AddChild(this._widget_1_5_0_1);
			this._widget_1_5_1 = new ButtonWidget(base.Context);
			this._widget_1_5.AddChild(this._widget_1_5_1);
			this._widget_1_5_1_0 = new InputKeyVisualWidget(base.Context);
			this._widget_1_5_1.AddChild(this._widget_1_5_1_0);
			this._widget_1_5_1_1 = new TextWidget(base.Context);
			this._widget_1_5_1.AddChild(this._widget_1_5_1_1);
			this._widget_1_6 = new ImageWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_6);
		}

		// Token: 0x06002AE2 RID: 10978 RVA: 0x001643CC File Offset: 0x001625CC
		public void SetIds()
		{
			this._widget_1_4_0_2.Id = "ClipRect";
			this._widget_1_4_0_2_0.Id = "ListPanel";
			this._widget_1_4_1.Id = "VerticalScrollbar";
			this._widget_1_4_1_1.Id = "VerticalScrollbarHandle";
		}

		// Token: 0x06002AE3 RID: 10979 RVA: 0x0016441C File Offset: 0x0016261C
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.StretchToParent;
			base.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0.Color = new Color(0f, 0f, 0f, 1f);
			this._widget_0.AlphaFactor = 0.6f;
			this._widget_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1.SuggestedWidth = 490f;
			this._widget_1.SuggestedHeight = 630f;
			this._widget_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_0.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\Popup\\canvas");
			this._widget_1_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_1.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\Popup\\canvas_gradient");
			this._widget_1_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_2.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_2.SuggestedHeight = 65f;
			this._widget_1_2.MarginTop = 5f;
			this._widget_1_2.Brush = base.Context.GetBrush("Crafting.History.Title");
			this._widget_1_3.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_3.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_3.SuggestedHeight = 26f;
			this._widget_1_3.MarginTop = 65f;
			this._widget_1_3.MarginLeft = -10f;
			this._widget_1_3.MarginRight = -10f;
			this._widget_1_3.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\Popup\\divider");
			this._widget_1_4.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4.Sprite = base.Context.SpriteData.GetSprite("scrollable_field_9");
			this._widget_1_4.MarginLeft = 16f;
			this._widget_1_4.MarginRight = 16f;
			this._widget_1_4.MarginTop = 95f;
			this._widget_1_4.MarginBottom = 95f;
			this._widget_1_4_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_0.MarginRight = 8f;
			this._widget_1_4_0.ClipRect = this._widget_1_4_0_2;
			this._widget_1_4_0.AutoHideScrollBars = true;
			this._widget_1_4_0.InnerPanel = this._widget_1_4_0_2_0;
			this._widget_1_4_0.VerticalScrollbar = this._widget_1_4_1;
			this._widget_1_4_0_0.CollectionParent = this._widget_1_4_0;
			this._widget_1_4_0_1.ScopeID = "CraftingHistoryPopupScope";
			this._widget_1_4_0_1.ScopeParent = this._widget_1_4_0_2;
			this._widget_1_4_0_1.ScopeMovements = GamepadNavigationTypes.Vertical;
			this._widget_1_4_0_2.ClipContents = true;
			this._widget_1_4_0_2.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_0_2.MarginLeft = 15f;
			this._widget_1_4_0_2.MarginRight = 15f;
			this._widget_1_4_0_2.MarginTop = 15f;
			this._widget_1_4_0_2.MarginBottom = 15f;
			this._widget_1_4_0_2_0.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_0_2_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_4_0_2_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
			this._widget_1_4_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_4_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_1.SuggestedWidth = 6f;
			this._widget_1_4_1.HorizontalAlignment = HorizontalAlignment.Right;
			this._widget_1_4_1.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_4_1.MarginRight = 8f;
			this._widget_1_4_1.MarginTop = 15f;
			this._widget_1_4_1.MarginBottom = 15f;
			this._widget_1_4_1.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_1_4_1.Handle = this._widget_1_4_1_1;
			this._widget_1_4_1.MaxValue = 100f;
			this._widget_1_4_1.MinValue = 0f;
			this._widget_1_4_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_4_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_4_1_0.SuggestedWidth = 3f;
			this._widget_1_4_1_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_4_1_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_1_4_1_0.AlphaFactor = 0.2f;
			this._widget_1_4_1_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_1_4_1_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_4_1_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_4_1_1.SuggestedWidth = 6f;
			this._widget_1_4_1_1.SuggestedHeight = 10f;
			this._widget_1_4_1_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1_4_1_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
			this._widget_1_5.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_5.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_1_5.StackLayout.LayoutMethod = LayoutMethod.HorizontalSpaced;
			this._widget_1_5.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_1_5.MarginBottom = 27f;
			this._widget_1_5.MarginLeft = 14f;
			this._widget_1_5.MarginRight = 14f;
			this._widget_1_5_0.DoNotPassEventsToChildren = true;
			this._widget_1_5_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_0.SuggestedWidth = 227f;
			this._widget_1_5_0.SuggestedHeight = 40f;
			this._widget_1_5_0.Brush = base.Context.GetBrush("ButtonBrush3");
			this._widget_1_5_0_0.DoNotAcceptEvents = true;
			this._widget_1_5_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_0_0.SuggestedWidth = 48f;
			this._widget_1_5_0_0.SuggestedHeight = 48f;
			this._widget_1_5_0_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_1_5_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_5_0_0.PositionXOffset = 12f;
			this._widget_1_5_0_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_5_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_5_0_1.MarginLeft = 7f;
			this._widget_1_5_0_1.MarginRight = 7f;
			this._widget_1_5_0_1.Brush = base.Context.GetBrush("Crafting.History.Control.Button.Text");
			this._widget_1_5_1.DoNotPassEventsToChildren = true;
			this._widget_1_5_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_1.SuggestedWidth = 227f;
			this._widget_1_5_1.SuggestedHeight = 40f;
			this._widget_1_5_1.Brush = base.Context.GetBrush("ButtonBrush1");
			this._widget_1_5_1_0.DoNotAcceptEvents = true;
			this._widget_1_5_1_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_1_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1_5_1_0.SuggestedWidth = 48f;
			this._widget_1_5_1_0.SuggestedHeight = 48f;
			this._widget_1_5_1_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_1_5_1_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_1_5_1_0.PositionXOffset = 12f;
			this._widget_1_5_1_1.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_5_1_1.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_5_1_1.MarginLeft = 7f;
			this._widget_1_5_1_1.MarginRight = 7f;
			this._widget_1_5_1_1.Brush = base.Context.GetBrush("Crafting.History.Control.Button.Text");
			this._widget_1_6.DoNotAcceptEvents = true;
			this._widget_1_6.WidthSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_6.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_1_6.MarginLeft = -20f;
			this._widget_1_6.MarginTop = -20f;
			this._widget_1_6.MarginRight = -20f;
			this._widget_1_6.MarginBottom = -20f;
			this._widget_1_6.Sprite = base.Context.SpriteData.GetSprite("frame_9");
		}

		// Token: 0x06002AE4 RID: 10980 RVA: 0x00164C94 File Offset: 0x00162E94
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_5_0.EventFire -= this.EventListenerOf_widget_1_5_0;
				this._widget_1_5_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_1.EventFire -= this.EventListenerOf_widget_1_5_1;
				this._widget_1_5_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1_1;
				if (this._datasource_Root_CraftingHistory != null)
				{
					this._datasource_Root_CraftingHistory.ListChanged -= this.OnList_datasource_Root_CraftingHistoryChanged;
					for (int i = this._widget_1_4_0_2_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_4_0_2_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child).OnBeforeRemovedChild(child);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)this._widget_1_4_0_2_0.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_CraftingHistory = null;
				}
				if (this._datasource_Root_CancelKey != null)
				{
					this._datasource_Root_CancelKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey;
					this._widget_1_5_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_0_0;
					this._datasource_Root_CancelKey = null;
				}
				if (this._datasource_Root_DoneKey != null)
				{
					this._datasource_Root_DoneKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey;
					this._widget_1_5_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1_0;
					this._datasource_Root_DoneKey = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06002AE5 RID: 10981 RVA: 0x001654B9 File Offset: 0x001636B9
		public void SetDataSource(CraftingHistoryVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06002AE6 RID: 10982 RVA: 0x001654C2 File Offset: 0x001636C2
		private void EventListenerOf_widget_1_5_0(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteCancel();
			}
		}

		// Token: 0x06002AE7 RID: 10983 RVA: 0x001654DC File Offset: 0x001636DC
		private void EventListenerOf_widget_1_5_1(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteDone();
			}
		}

		// Token: 0x06002AE8 RID: 10984 RVA: 0x001654F6 File Offset: 0x001636F6
		private void PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AE9 RID: 10985 RVA: 0x001654FF File Offset: 0x001636FF
		private void boolPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AEA RID: 10986 RVA: 0x00165508 File Offset: 0x00163708
		private void floatPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AEB RID: 10987 RVA: 0x00165511 File Offset: 0x00163711
		private void Vec2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AEC RID: 10988 RVA: 0x0016551A File Offset: 0x0016371A
		private void Vector2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AED RID: 10989 RVA: 0x00165523 File Offset: 0x00163723
		private void doublePropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AEE RID: 10990 RVA: 0x0016552C File Offset: 0x0016372C
		private void intPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AEF RID: 10991 RVA: 0x00165535 File Offset: 0x00163735
		private void uintPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AF0 RID: 10992 RVA: 0x0016553E File Offset: 0x0016373E
		private void ColorPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06002AF1 RID: 10993 RVA: 0x00165547 File Offset: 0x00163747
		private void HandleWidgetPropertyChangeOf_widget_1_2(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.TitleText = this._widget_1_2.Text;
				return;
			}
		}

		// Token: 0x06002AF2 RID: 10994 RVA: 0x0016556D File Offset: 0x0016376D
		private void PropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF3 RID: 10995 RVA: 0x00165576 File Offset: 0x00163776
		private void boolPropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF4 RID: 10996 RVA: 0x0016557F File Offset: 0x0016377F
		private void floatPropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF5 RID: 10997 RVA: 0x00165588 File Offset: 0x00163788
		private void Vec2PropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF6 RID: 10998 RVA: 0x00165591 File Offset: 0x00163791
		private void Vector2PropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF7 RID: 10999 RVA: 0x0016559A File Offset: 0x0016379A
		private void doublePropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF8 RID: 11000 RVA: 0x001655A3 File Offset: 0x001637A3
		private void intPropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AF9 RID: 11001 RVA: 0x001655AC File Offset: 0x001637AC
		private void uintPropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AFA RID: 11002 RVA: 0x001655B5 File Offset: 0x001637B5
		private void ColorPropertyChangedListenerOf_widget_1_5_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_1(propertyName);
		}

		// Token: 0x06002AFB RID: 11003 RVA: 0x001655BE File Offset: 0x001637BE
		private void HandleWidgetPropertyChangeOf_widget_1_5_0_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.CancelText = this._widget_1_5_0_1.Text;
				return;
			}
		}

		// Token: 0x06002AFC RID: 11004 RVA: 0x001655E4 File Offset: 0x001637E4
		private void PropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002AFD RID: 11005 RVA: 0x001655ED File Offset: 0x001637ED
		private void boolPropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002AFE RID: 11006 RVA: 0x001655F6 File Offset: 0x001637F6
		private void floatPropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002AFF RID: 11007 RVA: 0x001655FF File Offset: 0x001637FF
		private void Vec2PropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B00 RID: 11008 RVA: 0x00165608 File Offset: 0x00163808
		private void Vector2PropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B01 RID: 11009 RVA: 0x00165611 File Offset: 0x00163811
		private void doublePropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B02 RID: 11010 RVA: 0x0016561A File Offset: 0x0016381A
		private void intPropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B03 RID: 11011 RVA: 0x00165623 File Offset: 0x00163823
		private void uintPropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B04 RID: 11012 RVA: 0x0016562C File Offset: 0x0016382C
		private void ColorPropertyChangedListenerOf_widget_1_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1(propertyName);
		}

		// Token: 0x06002B05 RID: 11013 RVA: 0x00165635 File Offset: 0x00163835
		private void HandleWidgetPropertyChangeOf_widget_1_5_1(string propertyName)
		{
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root.IsDoneAvailable = this._widget_1_5_1.IsEnabled;
				return;
			}
		}

		// Token: 0x06002B06 RID: 11014 RVA: 0x0016565B File Offset: 0x0016385B
		private void PropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B07 RID: 11015 RVA: 0x00165664 File Offset: 0x00163864
		private void boolPropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B08 RID: 11016 RVA: 0x0016566D File Offset: 0x0016386D
		private void floatPropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B09 RID: 11017 RVA: 0x00165676 File Offset: 0x00163876
		private void Vec2PropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0A RID: 11018 RVA: 0x0016567F File Offset: 0x0016387F
		private void Vector2PropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0B RID: 11019 RVA: 0x00165688 File Offset: 0x00163888
		private void doublePropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0C RID: 11020 RVA: 0x00165691 File Offset: 0x00163891
		private void intPropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0D RID: 11021 RVA: 0x0016569A File Offset: 0x0016389A
		private void uintPropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0E RID: 11022 RVA: 0x001656A3 File Offset: 0x001638A3
		private void ColorPropertyChangedListenerOf_widget_1_5_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_1(propertyName);
		}

		// Token: 0x06002B0F RID: 11023 RVA: 0x001656AC File Offset: 0x001638AC
		private void HandleWidgetPropertyChangeOf_widget_1_5_1_1(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.DoneText = this._widget_1_5_1_1.Text;
				return;
			}
		}

		// Token: 0x06002B10 RID: 11024 RVA: 0x001656D2 File Offset: 0x001638D2
		private void PropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B11 RID: 11025 RVA: 0x001656DB File Offset: 0x001638DB
		private void boolPropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B12 RID: 11026 RVA: 0x001656E4 File Offset: 0x001638E4
		private void floatPropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B13 RID: 11027 RVA: 0x001656ED File Offset: 0x001638ED
		private void Vec2PropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B14 RID: 11028 RVA: 0x001656F6 File Offset: 0x001638F6
		private void Vector2PropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B15 RID: 11029 RVA: 0x001656FF File Offset: 0x001638FF
		private void doublePropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B16 RID: 11030 RVA: 0x00165708 File Offset: 0x00163908
		private void intPropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B17 RID: 11031 RVA: 0x00165711 File Offset: 0x00163911
		private void uintPropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B18 RID: 11032 RVA: 0x0016571A File Offset: 0x0016391A
		private void ColorPropertyChangedListenerOf_widget_1_5_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_0_0(propertyName);
		}

		// Token: 0x06002B19 RID: 11033 RVA: 0x00165724 File Offset: 0x00163924
		private void HandleWidgetPropertyChangeOf_widget_1_5_0_0(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root_CancelKey.KeyID = this._widget_1_5_0_0.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_CancelKey.IsVisible = this._widget_1_5_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x06002B1A RID: 11034 RVA: 0x00165779 File Offset: 0x00163979
		private void PropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B1B RID: 11035 RVA: 0x00165782 File Offset: 0x00163982
		private void boolPropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B1C RID: 11036 RVA: 0x0016578B File Offset: 0x0016398B
		private void floatPropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B1D RID: 11037 RVA: 0x00165794 File Offset: 0x00163994
		private void Vec2PropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B1E RID: 11038 RVA: 0x0016579D File Offset: 0x0016399D
		private void Vector2PropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B1F RID: 11039 RVA: 0x001657A6 File Offset: 0x001639A6
		private void doublePropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B20 RID: 11040 RVA: 0x001657AF File Offset: 0x001639AF
		private void intPropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B21 RID: 11041 RVA: 0x001657B8 File Offset: 0x001639B8
		private void uintPropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B22 RID: 11042 RVA: 0x001657C1 File Offset: 0x001639C1
		private void ColorPropertyChangedListenerOf_widget_1_5_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_5_1_0(propertyName);
		}

		// Token: 0x06002B23 RID: 11043 RVA: 0x001657CC File Offset: 0x001639CC
		private void HandleWidgetPropertyChangeOf_widget_1_5_1_0(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root_DoneKey.KeyID = this._widget_1_5_1_0.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_DoneKey.IsVisible = this._widget_1_5_1_0.IsVisible;
				return;
			}
		}

		// Token: 0x06002B24 RID: 11044 RVA: 0x00165821 File Offset: 0x00163A21
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B25 RID: 11045 RVA: 0x0016582F File Offset: 0x00163A2F
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B26 RID: 11046 RVA: 0x0016583D File Offset: 0x00163A3D
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B27 RID: 11047 RVA: 0x0016584B File Offset: 0x00163A4B
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B28 RID: 11048 RVA: 0x00165859 File Offset: 0x00163A59
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B29 RID: 11049 RVA: 0x00165867 File Offset: 0x00163A67
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B2A RID: 11050 RVA: 0x00165875 File Offset: 0x00163A75
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B2B RID: 11051 RVA: 0x00165883 File Offset: 0x00163A83
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B2C RID: 11052 RVA: 0x00165891 File Offset: 0x00163A91
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06002B2D RID: 11053 RVA: 0x001658A0 File Offset: 0x00163AA0
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "CraftingHistory")
			{
				this.RefreshDataSource_datasource_Root_CraftingHistory(this._datasource_Root.CraftingHistory);
				return;
			}
			if (propertyName == "CancelKey")
			{
				this.RefreshDataSource_datasource_Root_CancelKey(this._datasource_Root.CancelKey);
				return;
			}
			if (propertyName == "DoneKey")
			{
				this.RefreshDataSource_datasource_Root_DoneKey(this._datasource_Root.DoneKey);
				return;
			}
			if (propertyName == "TitleText")
			{
				this._widget_1_2.Text = this._datasource_Root.TitleText;
				return;
			}
			if (propertyName == "CancelText")
			{
				this._widget_1_5_0_1.Text = this._datasource_Root.CancelText;
				return;
			}
			if (propertyName == "IsDoneAvailable")
			{
				this._widget_1_5_1.IsEnabled = this._datasource_Root.IsDoneAvailable;
				return;
			}
			if (propertyName == "DoneText")
			{
				this._widget_1_5_1_1.Text = this._datasource_Root.DoneText;
				return;
			}
		}

		// Token: 0x06002B2E RID: 11054 RVA: 0x0016599A File Offset: 0x00163B9A
		private void ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B2F RID: 11055 RVA: 0x001659A8 File Offset: 0x00163BA8
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B30 RID: 11056 RVA: 0x001659B6 File Offset: 0x00163BB6
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B31 RID: 11057 RVA: 0x001659C4 File Offset: 0x00163BC4
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B32 RID: 11058 RVA: 0x001659D2 File Offset: 0x00163BD2
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B33 RID: 11059 RVA: 0x001659E0 File Offset: 0x00163BE0
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B34 RID: 11060 RVA: 0x001659EE File Offset: 0x00163BEE
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B35 RID: 11061 RVA: 0x001659FC File Offset: 0x00163BFC
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B36 RID: 11062 RVA: 0x00165A0A File Offset: 0x00163C0A
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(e.PropertyName);
		}

		// Token: 0x06002B37 RID: 11063 RVA: 0x00165A18 File Offset: 0x00163C18
		private void HandleViewModelPropertyChangeOf_datasource_Root_CancelKey(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget_1_5_0_0.KeyID = this._datasource_Root_CancelKey.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget_1_5_0_0.IsVisible = this._datasource_Root_CancelKey.IsVisible;
				return;
			}
		}

		// Token: 0x06002B38 RID: 11064 RVA: 0x00165A6D File Offset: 0x00163C6D
		private void ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B39 RID: 11065 RVA: 0x00165A7B File Offset: 0x00163C7B
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3A RID: 11066 RVA: 0x00165A89 File Offset: 0x00163C89
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3B RID: 11067 RVA: 0x00165A97 File Offset: 0x00163C97
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3C RID: 11068 RVA: 0x00165AA5 File Offset: 0x00163CA5
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3D RID: 11069 RVA: 0x00165AB3 File Offset: 0x00163CB3
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3E RID: 11070 RVA: 0x00165AC1 File Offset: 0x00163CC1
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B3F RID: 11071 RVA: 0x00165ACF File Offset: 0x00163CCF
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B40 RID: 11072 RVA: 0x00165ADD File Offset: 0x00163CDD
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(e.PropertyName);
		}

		// Token: 0x06002B41 RID: 11073 RVA: 0x00165AEC File Offset: 0x00163CEC
		private void HandleViewModelPropertyChangeOf_datasource_Root_DoneKey(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget_1_5_1_0.KeyID = this._datasource_Root_DoneKey.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget_1_5_1_0.IsVisible = this._datasource_Root_DoneKey.IsVisible;
				return;
			}
		}

		// Token: 0x06002B42 RID: 11074 RVA: 0x00165B44 File Offset: 0x00163D44
		public void OnList_datasource_Root_CraftingHistoryChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case ListChangedType.Reset:
				for (int i = this._widget_1_4_0_2_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_4_0_2_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_4_0_2_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_4_0_2_0.RemoveChild(child2);
				}
				return;
			case ListChangedType.Sorted:
				for (int j = 0; j < this._datasource_Root_CraftingHistory.Count; j++)
				{
					WeaponDesignSelectorVM bindingObject = this._datasource_Root_CraftingHistory[j];
					this._widget_1_4_0_2_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case ListChangedType.ItemAdded:
			{
				Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate);
				WeaponDesignSelectorVM weaponDesignSelectorVM = this._datasource_Root_CraftingHistory[e.NewIndex];
				generatedWidgetData.Data = weaponDesignSelectorVM;
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_4_0_2_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate, e.NewIndex);
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.CreateWidgets();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetIds();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetAttributes();
				crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetDataSource(weaponDesignSelectorVM);
				return;
			}
			case ListChangedType.ItemBeforeDeleted:
			{
				Widget child3 = this._widget_1_4_0_2_0.GetChild(e.NewIndex);
				((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case ListChangedType.ItemDeleted:
			{
				Widget child4 = this._widget_1_4_0_2_0.GetChild(e.NewIndex);
				((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_4_0_2_0.RemoveChild(child4);
				break;
			}
			case ListChangedType.ItemChanged:
				break;
			default:
				return;
			}
		}

		// Token: 0x06002B43 RID: 11075 RVA: 0x00165CE0 File Offset: 0x00163EE0
		private void RefreshDataSource_datasource_Root(CraftingHistoryVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_5_0.EventFire -= this.EventListenerOf_widget_1_5_0;
				this._widget_1_5_0_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_1.EventFire -= this.EventListenerOf_widget_1_5_1;
				this._widget_1_5_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1_1;
				if (this._datasource_Root_CraftingHistory != null)
				{
					this._datasource_Root_CraftingHistory.ListChanged -= this.OnList_datasource_Root_CraftingHistoryChanged;
					for (int i = this._widget_1_4_0_2_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_4_0_2_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_1_4_0_2_0.GetChild(i);
						((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child2).SetDataSource(null);
						this._widget_1_4_0_2_0.RemoveChild(child2);
					}
					this._datasource_Root_CraftingHistory = null;
				}
				if (this._datasource_Root_CancelKey != null)
				{
					this._datasource_Root_CancelKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey;
					this._widget_1_5_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_0_0;
					this._datasource_Root_CancelKey = null;
				}
				if (this._datasource_Root_DoneKey != null)
				{
					this._datasource_Root_DoneKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey;
					this._widget_1_5_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1_0;
					this._datasource_Root_DoneKey = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget_1_2.Text = this._datasource_Root.TitleText;
				this._widget_1_2.PropertyChanged += this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_5_0.EventFire += this.EventListenerOf_widget_1_5_0;
				this._widget_1_5_0_1.Text = this._datasource_Root.CancelText;
				this._widget_1_5_0_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_0_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_0_1;
				this._widget_1_5_1.IsEnabled = this._datasource_Root.IsDoneAvailable;
				this._widget_1_5_1.EventFire += this.EventListenerOf_widget_1_5_1;
				this._widget_1_5_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_1;
				this._widget_1_5_1_1.Text = this._datasource_Root.DoneText;
				this._widget_1_5_1_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_1_1;
				this._widget_1_5_1_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_1_1;
				this._datasource_Root_CraftingHistory = this._datasource_Root.CraftingHistory;
				if (this._datasource_Root_CraftingHistory != null)
				{
					this._datasource_Root_CraftingHistory.ListChanged += this.OnList_datasource_Root_CraftingHistoryChanged;
					for (int j = 0; j < this._datasource_Root_CraftingHistory.Count; j++)
					{
						Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate);
						WeaponDesignSelectorVM weaponDesignSelectorVM = this._datasource_Root_CraftingHistory[j];
						generatedWidgetData.Data = weaponDesignSelectorVM;
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_1_4_0_2_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate, j);
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.CreateWidgets();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetIds();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetAttributes();
						crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetDataSource(weaponDesignSelectorVM);
					}
				}
				this._datasource_Root_CancelKey = this._datasource_Root.CancelKey;
				if (this._datasource_Root_CancelKey != null)
				{
					this._datasource_Root_CancelKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey;
					this._datasource_Root_CancelKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey;
					this._widget_1_5_0_0.KeyID = this._datasource_Root_CancelKey.KeyID;
					this._widget_1_5_0_0.IsVisible = this._datasource_Root_CancelKey.IsVisible;
					this._widget_1_5_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_0_0;
					this._widget_1_5_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_0_0;
				}
				this._datasource_Root_DoneKey = this._datasource_Root.DoneKey;
				if (this._datasource_Root_DoneKey != null)
				{
					this._datasource_Root_DoneKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey;
					this._datasource_Root_DoneKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey;
					this._widget_1_5_1_0.KeyID = this._datasource_Root_DoneKey.KeyID;
					this._widget_1_5_1_0.IsVisible = this._datasource_Root_DoneKey.IsVisible;
					this._widget_1_5_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_1_0;
					this._widget_1_5_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_1_0;
				}
			}
		}

		// Token: 0x06002B44 RID: 11076 RVA: 0x00166E30 File Offset: 0x00165030
		private void RefreshDataSource_datasource_Root_CraftingHistory(MBBindingList<WeaponDesignSelectorVM> newDataSource)
		{
			if (this._datasource_Root_CraftingHistory != null)
			{
				this._datasource_Root_CraftingHistory.ListChanged -= this.OnList_datasource_Root_CraftingHistoryChanged;
				for (int i = this._widget_1_4_0_2_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_4_0_2_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_4_0_2_0.GetChild(i);
					((Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_4_0_2_0.RemoveChild(child2);
				}
				this._datasource_Root_CraftingHistory = null;
			}
			this._datasource_Root_CraftingHistory = newDataSource;
			this._datasource_Root_CraftingHistory = this._datasource_Root.CraftingHistory;
			if (this._datasource_Root_CraftingHistory != null)
			{
				this._datasource_Root_CraftingHistory.ListChanged += this.OnList_datasource_Root_CraftingHistoryChanged;
				for (int j = 0; j < this._datasource_Root_CraftingHistory.Count; j++)
				{
					Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate = new Crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate);
					WeaponDesignSelectorVM weaponDesignSelectorVM = this._datasource_Root_CraftingHistory[j];
					generatedWidgetData.Data = weaponDesignSelectorVM;
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_4_0_2_0.AddChildAtIndex(crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate, j);
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.CreateWidgets();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetIds();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetAttributes();
					crafting__TaleWorlds_CampaignSystem_ViewModelCollection_WeaponCrafting_CraftingVM_Dependency_32_ItemTemplate.SetDataSource(weaponDesignSelectorVM);
				}
			}
		}

		// Token: 0x06002B45 RID: 11077 RVA: 0x00166F6C File Offset: 0x0016516C
		private void RefreshDataSource_datasource_Root_CancelKey(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root_CancelKey != null)
			{
				this._datasource_Root_CancelKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey;
				this._widget_1_5_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_0_0;
				this._datasource_Root_CancelKey = null;
			}
			this._datasource_Root_CancelKey = newDataSource;
			this._datasource_Root_CancelKey = this._datasource_Root.CancelKey;
			if (this._datasource_Root_CancelKey != null)
			{
				this._datasource_Root_CancelKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CancelKey;
				this._datasource_Root_CancelKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CancelKey;
				this._widget_1_5_0_0.KeyID = this._datasource_Root_CancelKey.KeyID;
				this._widget_1_5_0_0.IsVisible = this._datasource_Root_CancelKey.IsVisible;
				this._widget_1_5_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_0_0;
				this._widget_1_5_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_0_0;
			}
		}

		// Token: 0x06002B46 RID: 11078 RVA: 0x00167318 File Offset: 0x00165518
		private void RefreshDataSource_datasource_Root_DoneKey(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root_DoneKey != null)
			{
				this._datasource_Root_DoneKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey;
				this._widget_1_5_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_5_1_0;
				this._datasource_Root_DoneKey = null;
			}
			this._datasource_Root_DoneKey = newDataSource;
			this._datasource_Root_DoneKey = this._datasource_Root.DoneKey;
			if (this._datasource_Root_DoneKey != null)
			{
				this._datasource_Root_DoneKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneKey;
				this._datasource_Root_DoneKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneKey;
				this._widget_1_5_1_0.KeyID = this._datasource_Root_DoneKey.KeyID;
				this._widget_1_5_1_0.IsVisible = this._datasource_Root_DoneKey.IsVisible;
				this._widget_1_5_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_5_1_0;
				this._widget_1_5_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_5_1_0;
			}
		}

		// Token: 0x0400091C RID: 2332
		private Widget _widget;

		// Token: 0x0400091D RID: 2333
		private Widget _widget_0;

		// Token: 0x0400091E RID: 2334
		private Widget _widget_1;

		// Token: 0x0400091F RID: 2335
		private ImageWidget _widget_1_0;

		// Token: 0x04000920 RID: 2336
		private ImageWidget _widget_1_1;

		// Token: 0x04000921 RID: 2337
		private TextWidget _widget_1_2;

		// Token: 0x04000922 RID: 2338
		private ImageWidget _widget_1_3;

		// Token: 0x04000923 RID: 2339
		private Widget _widget_1_4;

		// Token: 0x04000924 RID: 2340
		private ScrollablePanel _widget_1_4_0;

		// Token: 0x04000925 RID: 2341
		private NavigationForcedScopeCollectionTargeter _widget_1_4_0_0;

		// Token: 0x04000926 RID: 2342
		private NavigationScopeTargeter _widget_1_4_0_1;

		// Token: 0x04000927 RID: 2343
		private Widget _widget_1_4_0_2;

		// Token: 0x04000928 RID: 2344
		private NavigatableListPanel _widget_1_4_0_2_0;

		// Token: 0x04000929 RID: 2345
		private ScrollbarWidget _widget_1_4_1;

		// Token: 0x0400092A RID: 2346
		private Widget _widget_1_4_1_0;

		// Token: 0x0400092B RID: 2347
		private ImageWidget _widget_1_4_1_1;

		// Token: 0x0400092C RID: 2348
		private ListPanel _widget_1_5;

		// Token: 0x0400092D RID: 2349
		private ButtonWidget _widget_1_5_0;

		// Token: 0x0400092E RID: 2350
		private InputKeyVisualWidget _widget_1_5_0_0;

		// Token: 0x0400092F RID: 2351
		private TextWidget _widget_1_5_0_1;

		// Token: 0x04000930 RID: 2352
		private ButtonWidget _widget_1_5_1;

		// Token: 0x04000931 RID: 2353
		private InputKeyVisualWidget _widget_1_5_1_0;

		// Token: 0x04000932 RID: 2354
		private TextWidget _widget_1_5_1_1;

		// Token: 0x04000933 RID: 2355
		private ImageWidget _widget_1_6;

		// Token: 0x04000934 RID: 2356
		private CraftingHistoryVM _datasource_Root;

		// Token: 0x04000935 RID: 2357
		private MBBindingList<WeaponDesignSelectorVM> _datasource_Root_CraftingHistory;

		// Token: 0x04000936 RID: 2358
		private InputKeyItemVM _datasource_Root_CancelKey;

		// Token: 0x04000937 RID: 2359
		private InputKeyItemVM _datasource_Root_DoneKey;
	}
}
