using System;
using System.ComponentModel;
using TaleWorlds.CampaignSystem.ViewModelCollection.Party;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000148 RID: 328
	public class PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_6_Standard_VerticalScrollbar__DependendPrefab : Widget
	{
		// Token: 0x06005FFA RID: 24570 RVA: 0x002F55E2 File Offset: 0x002F37E2
		public PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_6_Standard_VerticalScrollbar__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x06005FFB RID: 24571 RVA: 0x002F55EC File Offset: 0x002F37EC
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new Widget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_3 = new ScrollbarWidget(base.Context);
			this._widget.AddChild(this._widget_3);
			this._widget_3_0 = new ImageWidget(base.Context);
			this._widget_3.AddChild(this._widget_3_0);
		}

		// Token: 0x06005FFC RID: 24572 RVA: 0x002F56AA File Offset: 0x002F38AA
		public void SetIds()
		{
			this._widget_2.Id = "ScrollbarBlocker";
			this._widget_3.Id = "Scrollbar";
			this._widget_3_0.Id = "ScrollbarHandle";
		}

		// Token: 0x06005FFD RID: 24573 RVA: 0x002F56DC File Offset: 0x002F38DC
		public void SetAttributes()
		{
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedWidth = 22f;
			base.SuggestedHeight = 800f;
			this._widget_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0.SuggestedWidth = 18f;
			this._widget_0.SuggestedHeight = 13f;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("General\\Scrollbar.Vertical1\\scroller_stop_top");
			this._widget_0.ExtendTop = 22f;
			this._widget_0.ExtendBottom = 22f;
			this._widget_0.ExtendLeft = 22f;
			this._widget_0.ExtendRight = 22f;
			this._widget_0.IsDisabled = true;
			this._widget_1.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_1.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_1.SuggestedWidth = 18f;
			this._widget_1.SuggestedHeight = 13f;
			this._widget_1.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_1.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_1.Sprite = base.Context.SpriteData.GetSprite("General\\Scrollbar.Vertical1\\scroller_stop_bottom");
			this._widget_1.ExtendTop = 22f;
			this._widget_1.ExtendBottom = 22f;
			this._widget_1.ExtendLeft = 22f;
			this._widget_1.ExtendRight = 22f;
			this._widget_1.IsDisabled = true;
			this._widget_2.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_2.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_2.SuggestedWidth = 22f;
			this._widget_2.SuggestedHeight = 800f;
			this._widget_2.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_2.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_2.MarginTop = 13f;
			this._widget_2.MarginBottom = 13f;
			this._widget_2.Sprite = base.Context.SpriteData.GetSprite("General\\Scrollbar.Vertical1\\scroller_bed_noscroll");
			this._widget_2.ExtendLeft = 20f;
			this._widget_2.ExtendRight = 20f;
			this._widget_2.ExtendTop = 20f;
			this._widget_2.ExtendBottom = 20f;
			this._widget_3.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_3.HeightSizePolicy = SizePolicy.StretchToParent;
			this._widget_3.SuggestedWidth = 22f;
			this._widget_3.SuggestedHeight = 800f;
			this._widget_3.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_3.VerticalAlignment = VerticalAlignment.Bottom;
			this._widget_3.MarginTop = 13f;
			this._widget_3.MarginBottom = 13f;
			this._widget_3.Brush = base.Context.GetBrush("Scrollbar.Vertical");
			this._widget_3.AlignmentAxis = AlignmentAxis.Vertical;
			this._widget_3.Handle = this._widget_3_0;
			this._widget_3.MaxValue = 100f;
			this._widget_3.MinValue = 0f;
			this._widget_3.UpdateChildrenStates = true;
			this._widget_3_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_3_0.SuggestedWidth = 20f;
			this._widget_3_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_3_0.VerticalAlignment = VerticalAlignment.Top;
			this._widget_3_0.Brush = base.Context.GetBrush("Scrollbar.Vertical.Handle");
			this._widget_3_0.MinHeight = 50f;
		}

		// Token: 0x06005FFE RID: 24574 RVA: 0x002F5A88 File Offset: 0x002F3C88
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root = null;
			}
		}

		// Token: 0x06005FFF RID: 24575 RVA: 0x002F5B76 File Offset: 0x002F3D76
		public void SetDataSource(PartyVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06006000 RID: 24576 RVA: 0x002F5B7F File Offset: 0x002F3D7F
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006001 RID: 24577 RVA: 0x002F5B8D File Offset: 0x002F3D8D
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006002 RID: 24578 RVA: 0x002F5B9B File Offset: 0x002F3D9B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006003 RID: 24579 RVA: 0x002F5BA9 File Offset: 0x002F3DA9
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006004 RID: 24580 RVA: 0x002F5BB7 File Offset: 0x002F3DB7
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006005 RID: 24581 RVA: 0x002F5BC5 File Offset: 0x002F3DC5
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006006 RID: 24582 RVA: 0x002F5BD3 File Offset: 0x002F3DD3
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006007 RID: 24583 RVA: 0x002F5BE1 File Offset: 0x002F3DE1
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006008 RID: 24584 RVA: 0x002F5BEF File Offset: 0x002F3DEF
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006009 RID: 24585 RVA: 0x002F5BFD File Offset: 0x002F3DFD
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
		}

		// Token: 0x0600600A RID: 24586 RVA: 0x002F5C00 File Offset: 0x002F3E00
		private void RefreshDataSource_datasource_Root(PartyVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			}
		}

		// Token: 0x0400137E RID: 4990
		private Widget _widget;

		// Token: 0x0400137F RID: 4991
		private Widget _widget_0;

		// Token: 0x04001380 RID: 4992
		private Widget _widget_1;

		// Token: 0x04001381 RID: 4993
		private Widget _widget_2;

		// Token: 0x04001382 RID: 4994
		private ScrollbarWidget _widget_3;

		// Token: 0x04001383 RID: 4995
		private ImageWidget _widget_3_0;

		// Token: 0x04001384 RID: 4996
		private PartyVM _datasource_Root;
	}
}
