using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.CampaignSystem.ViewModelCollection.Party.PartyTroopManagerPopUp;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;

namespace SandBox.GauntletUI.AutoGenerated1
{
	// Token: 0x02000159 RID: 345
	public class PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_23_Standard_PopupCloseButton__DependendPrefab : ButtonWidget
	{
		// Token: 0x06006870 RID: 26736 RVA: 0x0033EA9F File Offset: 0x0033CC9F
		public PartyScreen__TaleWorlds_CampaignSystem_ViewModelCollection_Party_PartyVM_Dependency_23_Standard_PopupCloseButton__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x06006871 RID: 26737 RVA: 0x0033EAA8 File Offset: 0x0033CCA8
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new TextWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new InputKeyVisualWidget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
		}

		// Token: 0x06006872 RID: 26738 RVA: 0x0033EB00 File Offset: 0x0033CD00
		public void SetIds()
		{
		}

		// Token: 0x06006873 RID: 26739 RVA: 0x0033EB04 File Offset: 0x0033CD04
		public void SetAttributes()
		{
			base.DoNotPassEventsToChildren = true;
			base.WidthSizePolicy = SizePolicy.Fixed;
			base.HeightSizePolicy = SizePolicy.Fixed;
			base.SuggestedWidth = 286f;
			base.SuggestedHeight = 82f;
			base.HorizontalAlignment = HorizontalAlignment.Center;
			base.VerticalAlignment = VerticalAlignment.Top;
			base.IsEnabled = true;
			base.Brush = base.Context.GetBrush("Standard.PopupCloseButton");
			base.UpdateChildrenStates = true;
			this._widget_0.DoNotAcceptEvents = true;
			this._widget_0.WidthSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
			this._widget_0.HorizontalAlignment = HorizontalAlignment.Center;
			this._widget_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0.Brush = base.Context.GetBrush("Standard.DialogCloseButtons.ButtonText");
			this._widget_0_0.DoNotAcceptEvents = true;
			this._widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
			this._widget_0_0.SuggestedWidth = 40f;
			this._widget_0_0.SuggestedHeight = 40f;
			this._widget_0_0.HorizontalAlignment = HorizontalAlignment.Left;
			this._widget_0_0.VerticalAlignment = VerticalAlignment.Center;
			this._widget_0_0.PositionXOffset = -40f;
			this._widget_0_0.PositionYOffset = -1f;
		}

		// Token: 0x06006874 RID: 26740 RVA: 0x0033EC44 File Offset: 0x0033CE44
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
					this._datasource_Root_DoneInputKey = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06006875 RID: 26741 RVA: 0x0033EFC8 File Offset: 0x0033D1C8
		public void SetDataSource(PartyRecruitTroopVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06006876 RID: 26742 RVA: 0x0033EFD1 File Offset: 0x0033D1D1
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteDone();
			}
		}

		// Token: 0x06006877 RID: 26743 RVA: 0x0033EFEB File Offset: 0x0033D1EB
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06006878 RID: 26744 RVA: 0x0033EFF4 File Offset: 0x0033D1F4
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06006879 RID: 26745 RVA: 0x0033EFFD File Offset: 0x0033D1FD
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687A RID: 26746 RVA: 0x0033F006 File Offset: 0x0033D206
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687B RID: 26747 RVA: 0x0033F00F File Offset: 0x0033D20F
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687C RID: 26748 RVA: 0x0033F018 File Offset: 0x0033D218
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687D RID: 26749 RVA: 0x0033F021 File Offset: 0x0033D221
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687E RID: 26750 RVA: 0x0033F02A File Offset: 0x0033D22A
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x0600687F RID: 26751 RVA: 0x0033F033 File Offset: 0x0033D233
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06006880 RID: 26752 RVA: 0x0033F03C File Offset: 0x0033D23C
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.DoneLbl = this._widget_0.Text;
				return;
			}
		}

		// Token: 0x06006881 RID: 26753 RVA: 0x0033F062 File Offset: 0x0033D262
		private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006882 RID: 26754 RVA: 0x0033F06B File Offset: 0x0033D26B
		private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006883 RID: 26755 RVA: 0x0033F074 File Offset: 0x0033D274
		private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006884 RID: 26756 RVA: 0x0033F07D File Offset: 0x0033D27D
		private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006885 RID: 26757 RVA: 0x0033F086 File Offset: 0x0033D286
		private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006886 RID: 26758 RVA: 0x0033F08F File Offset: 0x0033D28F
		private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006887 RID: 26759 RVA: 0x0033F098 File Offset: 0x0033D298
		private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006888 RID: 26760 RVA: 0x0033F0A1 File Offset: 0x0033D2A1
		private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x06006889 RID: 26761 RVA: 0x0033F0AA File Offset: 0x0033D2AA
		private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
		}

		// Token: 0x0600688A RID: 26762 RVA: 0x0033F0B4 File Offset: 0x0033D2B4
		private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root_DoneInputKey.KeyID = this._widget_0_0.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_DoneInputKey.IsVisible = this._widget_0_0.IsVisible;
				return;
			}
		}

		// Token: 0x0600688B RID: 26763 RVA: 0x0033F109 File Offset: 0x0033D309
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600688C RID: 26764 RVA: 0x0033F117 File Offset: 0x0033D317
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600688D RID: 26765 RVA: 0x0033F125 File Offset: 0x0033D325
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600688E RID: 26766 RVA: 0x0033F133 File Offset: 0x0033D333
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600688F RID: 26767 RVA: 0x0033F141 File Offset: 0x0033D341
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006890 RID: 26768 RVA: 0x0033F14F File Offset: 0x0033D34F
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006891 RID: 26769 RVA: 0x0033F15D File Offset: 0x0033D35D
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006892 RID: 26770 RVA: 0x0033F16B File Offset: 0x0033D36B
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006893 RID: 26771 RVA: 0x0033F179 File Offset: 0x0033D379
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06006894 RID: 26772 RVA: 0x0033F188 File Offset: 0x0033D388
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "DoneInputKey")
			{
				this.RefreshDataSource_datasource_Root_DoneInputKey(this._datasource_Root.DoneInputKey);
				return;
			}
			if (propertyName == "DoneLbl")
			{
				this._widget_0.Text = this._datasource_Root.DoneLbl;
				return;
			}
		}

		// Token: 0x06006895 RID: 26773 RVA: 0x0033F1D8 File Offset: 0x0033D3D8
		private void ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x06006896 RID: 26774 RVA: 0x0033F1E6 File Offset: 0x0033D3E6
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x06006897 RID: 26775 RVA: 0x0033F1F4 File Offset: 0x0033D3F4
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x06006898 RID: 26776 RVA: 0x0033F202 File Offset: 0x0033D402
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x06006899 RID: 26777 RVA: 0x0033F210 File Offset: 0x0033D410
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x0600689A RID: 26778 RVA: 0x0033F21E File Offset: 0x0033D41E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x0600689B RID: 26779 RVA: 0x0033F22C File Offset: 0x0033D42C
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x0600689C RID: 26780 RVA: 0x0033F23A File Offset: 0x0033D43A
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x0600689D RID: 26781 RVA: 0x0033F248 File Offset: 0x0033D448
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(e.PropertyName);
		}

		// Token: 0x0600689E RID: 26782 RVA: 0x0033F258 File Offset: 0x0033D458
		private void HandleViewModelPropertyChangeOf_datasource_Root_DoneInputKey(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
				return;
			}
		}

		// Token: 0x0600689F RID: 26783 RVA: 0x0033F2B0 File Offset: 0x0033D4B0
		private void RefreshDataSource_datasource_Root(PartyRecruitTroopVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
					this._datasource_Root_DoneInputKey = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget_0.Text = this._datasource_Root.DoneLbl;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._datasource_Root_DoneInputKey = this._datasource_Root.DoneInputKey;
				if (this._datasource_Root_DoneInputKey != null)
				{
					this._datasource_Root_DoneInputKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
					this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
					this._widget_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
					this._widget_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
					this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
					this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
				}
			}
		}

		// Token: 0x060068A0 RID: 26784 RVA: 0x0033F9F8 File Offset: 0x0033DBF8
		private void RefreshDataSource_datasource_Root_DoneInputKey(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root_DoneInputKey != null)
			{
				this._datasource_Root_DoneInputKey.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithValue -= this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue -= this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue -= this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue -= this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue -= this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue -= this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue -= this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value -= this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
				this._widget_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0_0;
				this._datasource_Root_DoneInputKey = null;
			}
			this._datasource_Root_DoneInputKey = newDataSource;
			this._datasource_Root_DoneInputKey = this._datasource_Root.DoneInputKey;
			if (this._datasource_Root_DoneInputKey != null)
			{
				this._datasource_Root_DoneInputKey.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithValue += this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithBoolValue += this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithIntValue += this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithFloatValue += this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithUIntValue += this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithColorValue += this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithDoubleValue += this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DoneInputKey;
				this._datasource_Root_DoneInputKey.PropertyChangedWithVec2Value += this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DoneInputKey;
				this._widget_0_0.KeyID = this._datasource_Root_DoneInputKey.KeyID;
				this._widget_0_0.IsVisible = this._datasource_Root_DoneInputKey.IsVisible;
				this._widget_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0_0;
				this._widget_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0_0;
			}
		}

		// Token: 0x04001512 RID: 5394
		private ButtonWidget _widget;

		// Token: 0x04001513 RID: 5395
		private TextWidget _widget_0;

		// Token: 0x04001514 RID: 5396
		private InputKeyVisualWidget _widget_0_0;

		// Token: 0x04001515 RID: 5397
		private PartyRecruitTroopVM _datasource_Root;

		// Token: 0x04001516 RID: 5398
		private InputKeyItemVM _datasource_Root_DoneInputKey;
	}
}
